cohere-ai/cohere-developer-experience

fern/pages/going-to-production/rate-limits.mdx

This pull request updates the "API Keys and Rate Limits" documentation page. It includes changes to the rate limits for various endpoints and production key specifications.
- Adds a description, image, and keywords to the document metadata.
- Updates the description of the document to specify that it covers limitations around Cohere's API.
- Modifies the rate limits for specific endpoints:
- Generate (legacy): 5/min
- Chat: 20/min (increased from 10/min)
- Summarize: 5/min
- Cluster: 5/min
- Embed: 5/min
- EmbedJob: 5/min
- Rerank: 10/min
- Reduces the rate limit for production keys from 10,000 calls per minute to 1,000 calls per minute.

Updating rate limits

---

fern/assets/input.css

This pull request removes the styling for the ``.code-block`` class, which previously had a light yellow background with a solid border. 
- `fern/assets/input.css`: Removes the ``.code-block`` class selector and its associated styles.

remove `.code-block` from custom css to fix code block rendering in dark mode

---

cohere-openapi.yaml
fern/pages/fine-tuning/chat-fine-tuning/chat-starting-the-training.mdx
fern/pages/fine-tuning/classify-fine-tuning/classify-starting-the-training.mdx
fern/pages/fine-tuning/fine-tuning-with-the-python-sdk.mdx
fern/pages/get-started/datasets.mdx
snippets/curl/finetuning/create-finetuned-model.sh
snippets/go/dataset-post/main.go
snippets/go/finetuning/create-finetuned-model/main.go
snippets/java/app/src/main/java/DatasetPost.java
snippets/java/app/src/main/java/finetuning/CreateFinetunedModel.java
snippets/java/app/src/main/java/finetuning/UpdateFinetunedModel.java
snippets/node/finetuning/create-finetuned-model.ts
snippets/python-async/dataset-post.py
snippets/python-async/embed-jobs-post.py
snippets/python-async/finetuning/create-finetuned-model.py
snippets/python/dataset-post.py
snippets/python/embed-jobs-post.py
snippets/python/finetuning/create-finetuned-model.py
snippets/python/finetuning/update-finetuned-model.py
snippets/snippets/curl/finetuning/create-finetuned-model.sh
snippets/snippets/go/dataset-post/main.go
snippets/snippets/go/finetuning/create-finetuned-model/main.go
snippets/snippets/java/app/src/main/java/DatasetPost.java
snippets/snippets/java/app/src/main/java/finetuning/CreateFinetunedModel.java
snippets/snippets/java/app/src/main/java/finetuning/UpdateFinetunedModel.java
snippets/snippets/node/finetuning/create-finetuned-model.ts
snippets/snippets/python-async/dataset-post.py
snippets/snippets/python/dataset-post.py

- fix: include missing imports for update_finetuned_model
- fix: multiple dataset api snippets
- fix: async create_finetuned_model
- fix: end `)` for print statements in classify finetune docs
- move from generative to chat finetune type in api examples / spec

multiple doc fixes + add documentation for new wandb param for chat finetunes

---

fern/pages/models/the-command-family-of-models/command-r-plus.mdx

This PR adds a new section to the end of the page, congratulating the reader on reaching the end and offering an API credit.
- A new section is added to the end of the page.
- The section congratulates the reader on reaching the end of the page.
- It offers an extra $1 API credit to the reader.
- The reader can enter the `CommandR+Docs` credit code in their Cohere dashboard to claim the credit.

Add note on credit

---

fern/pages/models/models.mdx

[GRO-2081 Update status for R and R+ on OCI from 'coming soon'](https://linear.app/cohereai/issue/GRO-2081/update-status-for-r-and-r-on-oci-from-coming-soon)
This PR updates the Amazon Bedrock Model IDs and Oracle OCI Generative AI Service IDs for the `command-r-plus`, `command-r`, and `command` models.
- The `command-r-plus` model ID has been updated to `cohere.command-r-plus-v1:0` and the Oracle OCI Generative AI Service ID to `cohere.command-r-plus v1.2`.
- The `command-r` model ID remains the same, but the Oracle OCI Generative AI Service ID has been updated to `cohere.command-r-16k v1.2`.
- The `command` model ID remains the same, but the Oracle OCI Generative AI Service ID has been updated to `cohere.command v15.6`.
- The `command-light` model ID remains the same, but the Oracle OCI …

Update Oracle Models

---

fern/assets/input.css

[GRO-2073](https://linear.app/cohereai/issue/GRO-2073/adjust-green-text-contrast-in-dark-mode-documentation)
This PR removes the `color` property from the `.fern-mdx-link` class in the `input.css` file.
- The `color` property is no longer set to `rgb(57 89 77)`.

Color of the links - dark mode

---

fern/pages/fine-tuning/chat-fine-tuning/chat-starting-the-training.mdx
fern/pages/fine-tuning/classify-fine-tuning/classify-preparing-the-data.mdx
fern/pages/fine-tuning/classify-fine-tuning/classify-starting-the-training.mdx
fern/pages/fine-tuning/fine-tuning-on-aws/fine-tuning-cohere-models-on-amazon-bedrock.mdx
fern/pages/fine-tuning/fine-tuning-on-aws/fine-tuning-cohere-models-on-amazon-sagemaker.mdx
fern/pages/fine-tuning/fine-tuning-with-the-cohere-dashboard.mdx
fern/pages/fine-tuning/fine-tuning-with-the-python-sdk.mdx
fern/pages/fine-tuning/rerank-fine-tuning/rerank-starting-the-training.mdx
fern/pages/fine-tuning/troubleshooting-a-fine-tuned-model.mdx

This PR introduces changes to the fine-tuning process, including updates to the terminology, dataset requirements, and job statuses. The changes aim to improve clarity and consistency in the documentation, ensuring a smoother experience for users.
- **Updated Terminology:** The PR replaces the term "fine-tune" with "fine-tuning job" throughout the documentation. This change provides a more accurate description of the process, emphasizing the job-like nature of fine-tuning tasks.
- **Dataset Requirements:** The PR updates the minimum dataset size requirements for various fine-tuning jobs. For classification fine-tuning jobs, the minimum number of examples is now **40**, with each label requiring at least **5** examples and at least **2** unique labels. For fine-tuning on Amazon Bedrock and …

docs(finetuning): remove all usages of the verb fine-tune as an adjective or a noun

---

fern/pages/fine-tuning/chat-fine-tuning/chat-starting-the-training.mdx
fern/pages/fine-tuning/rerank-fine-tuning/rerank-starting-the-training.mdx

This PR updates the `dataset_id` variable in the `create_finetuned_model` function. The changes are as follows:
- In `fern/pages/fine-tuning/chat-fine-tuning/chat-starting-the-training.mdx`, the `dataset_id` is changed from `my-chat_dataset.id` to `chat_dataset.id`.
- In `fern/pages/fine-tuning/rerank-fine-tuning/rerank-starting-the-training.mdx`, the `dataset_id` is changed from `my-rerank_dataset.id` to `rerank_dataset.id`.

fix: minor type for chat and rerank create_finetuned_model example

---

fern/docs.yml

This PR updates the `redirects` section in the `fern/docs.yml` file. It modifies the `source` and `destination` paths for a specific redirect rule.
- The `source` path is updated from `/docs/generation-card` to `/docs/data-statement`.
- The `destination` path is changed from `/docs/data-statement` to `/docs/usage-guidelines`.

(docs)Redirects to usage-guidelines

---

fern/docs.yml

This PR updates the `redirects` section in the `fern/docs.yml` file. It modifies the destination paths for specific source URLs, ensuring that users are directed to the correct documentation pages.
- The destination for the source `/docs/generation-card` is changed from `/docs/generation-benchmarks` to `/docs/usage-guidelines`.
- The destination for the source `/data-statement` is updated from `/docs/data-statement` to `/docs/usage-guidelines`.
- The destination for the source `/generation-card` is modified from `/docs/generation-card` to `/docs/usage-guidelines`.

(docs)last time I promise

---

fern/docs.yml

This PR removes the following redirects from the `redirects` list:
- `/generation-card` to `/docs/generation-card`
- `/docs/generation-card` to `/generation-card`
The PR also removes the `permanent` attribute from the redirect, which was previously set to `true`.

(docs)last of the last

---

fern/pages/text-generation/chat-api.mdx

Update chat-api.mdx - replaced string being passed to the "message" parameter in the co.chat api call with the "message" object defined above.
section: https://docs.cohere.com/docs/chat-api#multi-turn-conversations

Update chat-api.mdx - replaced string being passed to the "message" parameter

---

fern/pages/text-generation/streaming.mdx

current: (i.e. because of it was finished or there was an error).
proposed: (i.e. because it finished or due to an error).
section: https://docs.cohere.com/docs/streaming#stream-end

Update streaming.mdx - corrected typo in stream-end section

---

fern/pages/models/the-command-family-of-models/command-r-plus.mdx

The PR removes the section on the temporary context window caveat, which mentions a known issue with prompts between 112K and 128K in length resulting in bad generations.
- The section on the temporary context window caveat has been removed.

Remove CMDR+ caveat

---

fern/v1.yml

This pull request updates the API reference section of the `fern/v1.yml` file. It removes the V2 (beta) section and focuses on the v1 endpoints.
The changes include:
- Removing the V2 (beta) section, which includes the `/v2/chat` and `/v2/chat/stream` endpoints.
- Updating the section titles to use the "v1" prefix instead of the "/v1" prefix for consistency.
- Ensuring the API reference section is up-to-date with the latest v1 endpoints.

Clean up v1 config

---

fern/v2.yml

This PR makes changes to the `fern/v2.yml` file, specifically within the `navigation` section.
- The `page` titled "Migrating From API v1 to API v2" has been removed from the `navigation` section.
- A new `page` titled "Migrating From API v1 to API v2" has been added to the `navigation` section, with a `path` of "pages/v2/text-generation/migrating-v1-to-v2.mdx".

Move migration page

---

fern/v2.yml

This pull request adds a new line to the `fern/v2.yml` file, which sets the `paginated` property to `true`.
- The `paginated` property is set to `true` for the `api` section.

No scroll for v2

---

fern/v1.yml
fern/v2.yml

This pull request adds a new section to the navigation menu in both `fern/v1.yml` and `fern/v2.yml` files. The section is named `v1/check-api-key` and is configured to be hidden and skipped in the navigation. It contains a single entry, `POST /v1/check-api-key`, which is likely a new API endpoint.
- Added a new section named `v1/check-api-key` to the navigation menu.
- Set the `skip-slug` and `hidden` properties to `true` for the new section.
- Included a new entry `POST /v1/check-api-key` within the new section.

Hide check-api-key 

---

fern/docs.yml

This PR makes a simple change to the `fern/docs.yml` file, adding a new version entry for `v1`.
- A new version entry for `v1` is added to the `versions` list, with the path `v1.yml` and slug `v1`.

Make V2 the default version of guides

---

fern/pages/v2/text-generation/structured-outputs-json.mdx

This PR introduces a new `Info` component to the documentation, which replaces the previous `📘 Important` notation. This change enhances the visual clarity of the documentation by providing a more distinct and structured way to highlight important information.
- Replaces the `📘 Important` notation with the new `Info` component.
- Updates the text within the `Info` component to maintain consistency with the new formatting.
- Renames the `schema` parameter to `json_schema` for clarity and consistency.

Formatting for structured outputs guide

---

fern/docs.yml

This PR introduces a new announcement section to the `fern/docs.yml` file, informing users about the availability of new API V2 endpoints.
- A new `announcement` section is added, containing a message with a link to learn more about the new API V2 endpoints.
- The message is formatted with an emoji and a link to the Cohere blog for further details.

[Docs] Display API V2 announcement banner

---

fern/v2.yml

This pull request makes changes to the `fern/v2.yml` file, specifically to the `slug` values in the `navigation` section.
- The `slug` value for the `POST /v2/chat` endpoint is changed from `chat-v2` to `chat`.
- The `slug` value for the `STREAM /v2/chat` endpoint is changed from `chat-stream-v2` to `chat-stream`.

update chat v2 url slug to be /chat

---

fern/docs.yml
fern/pages/v2/text-embeddings/embeddings.mdx
fern/pages/v2/text-generation/migrating-v1-to-v2.mdx
fern/pages/v2/text-generation/prompt-engineering/preambles.mdx
fern/pages/v2/tutorials/build-things-with-cohere/rag-with-cohere.mdx

This PR introduces a new version of the documentation, `v2`, to the `fern/docs.yml` file.
- The `versions` section now includes a new entry for `v2`, with the path `v2.yml` and slug `v2`.
- This new version is added alongside the existing `v1` version, ensuring a clear distinction between the two.

Changing v1 back to the default.

---

fern/docs.yml

This PR updates the `display-name` field in the `fern/docs.yml` file. The changes are as follows:
- The `display-name` for the `v2` version is updated to `v2 API`.
- The `display-name` for the `v1` version is updated to `v1 API`.

Update version dropdown to include "API"

---

fern/pages/v2/fine-tuning/chat-fine-tuning/chat-starting-the-training.mdx

This PR introduces the ability to publish training metrics and hyperparameter values to a Weights and Biases account during the fine-tuning process of a Chat model. The `wandb` parameter is added to the `FinetunedModel` request, allowing users to specify a Weights and Biases configuration.
- A new section is added to the documentation, explaining the `wandb` parameter and its usage.
- The `WandbConfig` class is imported from `cohere.finetuning`.
- The `wandb` parameter is added to the `FinetunedModel` request, allowing users to specify a Weights and Biases configuration.
- An example configuration is provided, demonstrating how to define the `WandbConfig` with the `project`, `api_key`, and `entity` parameters.

fix: doc fixes post migration to v2

---

fern/pages/models/the-command-family-of-models/command-r-plus.mdx

The PR updates the documentation for the Command R+ model, adding information about the training data used.
- The updated models were trained with data through February 2023.

Adding knowledge cut off.

---

fern/pages/v2/text-generation/tools/tool-use.mdx

This PR introduces a new feature called the 'Streaming option' to the `tool-use.mdx` file. The 'Streaming option' allows for the streaming of responses from the `co.chat_stream` function, enabling the printing of final answers and citations in real-time.
- Added a new section titled 'Streaming option' to the file.
- Introduced a Python code block within the new section to demonstrate the streaming of responses.
- The code block initializes the `response` variable by calling the `co.chat_stream` function with specific model, message, and tool parameters.
- The code then enters a loop to process each `chunk` in the response.
- For each `chunk`, it checks its type and prints the content accordingly.
- If the `chunk` type is 'content-delta', it prints the message content text.
- If the …

Add tool use streaming snippets

---

fern/pages/going-to-production/rate-limits.mdx

This pull request updates the rate limits for Cohere's API keys, specifically the evaluation and production keys. The changes are as follows:
- The rate limit column has been renamed from `Evaluation rate limit` and `Production rate limit` to `Evaluation RPM limit` and `Production RPM limit` respectively.
- The rate limit values for each endpoint have been updated. For example, the `Chat` endpoint's evaluation rate limit has been changed from `20/min` to `20` and the production rate limit has been changed from `no limit` to `500`.
- The rate limit values for the `Embed`, `EmbedJob`, `Rerank`, `Generate (legacy)`, and `Summarize (legacy)` endpoints have also been updated, with the evaluation rate limits now expressed as a single number and the production rate limits adjusted.

Fix rate limit documentation

---

fern/pages/cohere-api/errors.mdx

This pull request removes the section on the 498 response code, which is sent when a request is blocked due to potential violations of the Usage Guidelines. The section on the 499 response code, which is sent when a user cancels a request, remains unchanged.
- The section on the 498 response code has been removed.

Undocument 498 errors

---

fern/pages/going-to-production/rate-limits.mdx

This PR introduces changes to the rate limits for Cohere's API keys, specifically the trial and production keys. The modifications include:
- Renaming the 'Evaluation rate limit' to 'Trial rate limit' to align with the new terminology.
- Updating the rate limits for various endpoints, such as reducing the rate limit for the 'Embed' endpoint from 100,000/min to 100/min for trial keys and introducing a limit of 2,000/min for production keys.
- Adding new endpoints like 'Tokenize' and 'Classify' with specific rate limits.
- Implementing a monthly limit of 1,000 calls for all endpoints with a trial key.
- Providing contact information for rate limit increase inquiries.
- The 'Evaluation' key is now referred to as a 'Trial' key, reflecting a change in terminology.
- Rate limits for specific …

Update rate limits

---

fern/pages/llm-university/intro-large-language-models/semantic-search-temp.mdx
fern/pages/llm-university/intro-semantic-search/multilingual-movie-search.mdx

This PR makes changes to the semantic search documentation.
- The text embedding section has been updated to include a link to the Cohere documentation.
- The section on using similarity to find the best document has been updated to include a link to the Cohere documentation.
- The 'Original Source' section has been removed.

Fixing some links.

---

fern/pages/going-to-production/rate-limits.mdx

This PR updates the rate limits for various Cohere API endpoints, ensuring accurate and up-to-date information for users. The changes include:
- Adding a new row for the `/reference/chat` endpoint, specifying a trial rate limit of 20/min and a production rate limit of 500/min.
- Introducing a new row for the `/reference/embed-images` endpoint, with a trial rate limit of 5/min and a production rate limit of 40/min.
- Adjusting the order of rows to maintain consistency and clarity.
- Removing the duplicate row for the `/reference/rerank` endpoint, ensuring a single entry with the correct rate limits.
- Removing the duplicate row for the `/reference/embed-jobs` endpoint, leaving only one entry with the appropriate rate limits.
- Moving the row for the `/reference/chat` endpoint to a more …

Add Image Embeddings rate limits

---

fern/assets/input.css

In scope of this PR we introduce change to make comment in code block section more contrast.
Change affects only light theme.
Before the change:
After the change:

Docs: make code block comment color more contrast

---

fern/pages/deployment-options/cohere-on-microsoft-azure.mdx
fern/pages/v2/deployment-options/cohere-on-microsoft-azure.mdx

This PR updates the list of available models through Azure AI Studio with pay-as-you-go, token-based billing. It adds refreshed versions of Command R and Command R+ that were released in August 2024 and are now available on Azure.
- Adds refreshed versions of Command R and Command R+ to the list of available models.
- Includes links to the refreshed models' documentation.
- Mentions the release date of the refreshed models and their availability on Azure.

Adding information about the refreshed models on Azure.

---

fern/pages/integrations/cohere-and-langchain.mdx

- Adds installation command for `langchain-cohere` package which is necessary for Cohere integrations
- Adds optional installation of `langchain-community` for third-party integrations

Update Langchain imports

---

fern/pages/v2/fine-tuning/classify-fine-tuning/classify-starting-the-training.mdx
fern/v2.yml

It was reported by site audit that we have duplicated titles on a couple pages so this change has to resove that issue
Pages with duplicated titles:
https://docs.cohere.com/v2/reference/createfinetunedmodel
https://docs.cohere.com/v2/docs/classify-starting-the-training

Fix duplicates titles on fine-tuning reference and fine tuning page

---

fern/pages/v2/text-generation/retrieval-augmented-generation-rag.mdx
fern/pages/v2/text-generation/structured-outputs-json.mdx

This PR doesn't contain any code changes, it contains only reformatter existing code snippets using black.

Format code snippets for text generation

---

fern/pages/models/rerank-2.mdx

...and the process for handling documents in cases where the combined number of tokens from the query + document exceed the context limit.

Update Rerank docs to clarify how tokens from the query and document are combined for each document

---

fern/pages/deployment-options/oracle-cloud-infrastructure-oci.mdx

- Removes Command and Command light from available models list
- Updates fine-tuning support information to specify Command R versions (command-r-04-2024 and command-r-08-2024)
- Adds reference link to OCI documentation for up-to-date model listings

Update OCI model availability

---

fern/pages/deployment-options/cohere-on-aws/amazon-sagemaker-setup-guide.mdx

Adds documentation for accessing Cohere models through Amazon SageMaker Jumpstart, providing step-by-step instructions for users to easily find and use Cohere models in the SageMaker Studio interface.

Add sagemaker jumpstart guide

---

fern/pages/deployment-options/cohere-on-aws/amazon-sagemaker-setup-guide.mdx

This PR adds a support email address to the Amazon SageMaker setup guide. The email address is provided to help users with any questions they may have about the process.
- A new line is added to the guide: `If you have any questions about this process, reach out to support@cohere.com.`

Adding a 'contact support' message.

---

fern/pages/v2/deployment-options/cohere-on-aws/amazon-bedrock.mdx
fern/pages/v2/deployment-options/cohere-on-aws/amazon-sagemaker-setup-guide.mdx
fern/pages/v2/deployment-options/cohere-on-microsoft-azure.mdx
fern/pages/v2/deployment-options/cohere-works-everywhere.mdx
fern/v2.yml

This PR updates the note on cloud deployments for v2 API. Also corrects one link in the yml to point to v2.

Update note on cloud deployments for v2 API

---

fern/pages/models/aya.mdx

This PR updates the slug for the Aya Family of Models page, changing it from `aya/tools` to `docs/aya`. This change ensures that the page is accessible at the correct URL.
- The slug for the Aya Family of Models page is updated to `docs/aya`.

Bad slug, missing link.

---

fern/pages/v2/fine-tuning/fine-tuning-with-the-python-sdk.mdx

It was reported that on v2 Programmatic Fine-tuning pages ([page1](https://docs.cohere.com/v2/docs/fine-tuning-with-the-python-sdk) [page2](https://docs.cohere.com/docs/fine-tuning-with-the-python-sdk)) we have chains of redicts that is recognized as an error in seo tools.
This PRs should fix the issue. I've used the [same approach](https://github.com/cohere-ai/cohere-developer-experience/blob/main/fern/pages/fine-tuning/fine-tuning-with-the-python-sdk.mdx?plain=1#L57) we used in other places which seems to resolve similar issues.

Fix chaines of redirects issue

---

fern/docs.yml

Adding redirects for Structured output tools pages
that has been introduces in this [PR](https://github.com/cohere-ai/cohere-developer-experience/pull/262/files)

Add redirects for structured outputs pages

---

fern/pages/responsible-use/responsible-use/usage-guidelines.mdx

This PR updates the `updatedAt` field in the `fern/pages/responsible-use/responsible-use/usage-guidelines.mdx` file.
- The `updatedAt` field is changed from `"Thu Nov 21 2024 09::48 GMT+0000 (Coordinated Universal Time)"` to `"Fr Nov 29 2024 09::48 GMT+0000 (Coordinated Universal Time)"`.
- The updated date is also reflected in the document's header, which now reads `(This document was updated on 11/29/2024)`.

It was pointed out that a link was missing, I've added.

---

fern/pages/text-embeddings/reranking/overview.mdx
fern/pages/tutorials/build-things-with-cohere/rag-with-cohere.mdx
fern/pages/tutorials/build-things-with-cohere/reranking-with-cohere.mdx
fern/pages/v2/tutorials/build-things-with-cohere/reranking-with-cohere.mdx

This pull request updates the slug for the "Rerank Overview" page from `docs/overview` to `docs/rerank-overview`. It also updates the links to the documentation on Rerank in several tutorial pages to reflect this change.
- The `slug` field in the `fern/pages/text-embeddings/reranking/overview.mdx` file is updated to `docs/rerank-overview`.
- The links to the documentation on Rerank in the following files are updated to `/docs/rerank-overview`:
- `fern/pages/tutorials/build-things-with-cohere/rag-with-cohere.mdx`
- `fern/pages/tutorials/build-things-with-cohere/reranking-with-cohere.mdx`
- `fern/pages/v2/tutorials/build-things-with-cohere/reranking-with-cohere.mdx`

Change rerank overview page slug

---

fern/pages/v2/deployment-options/cohere-works-everywhere.mdx

This PR adds a warning about the compatibility of the Rerank API with Bedrock.
- A new warning is added to the page, stating that Rerank 3.5 on Bedrock is only supported with Rerank API v2, via `BedrockClientV2()`.

Add warning about client version for Rerank on Bedrock

---

fern/pages/deployment-options/cohere-on-microsoft-azure.mdx
fern/pages/v2/deployment-options/cohere-on-microsoft-azure.mdx

- Added SDK usage examples for Command, Embed, and Rerank models
- Renamed "Azure AI Studio" to "Azure AI Foundry" and added link to official documentation

Add code snippets for azure using cohere sdk

---

fern/pages/integrations/cohere-and-langchain/chat-on-langchain.mdx
fern/pages/integrations/cohere-and-langchain/embed-on-langchain.mdx
fern/pages/integrations/cohere-and-langchain/rerank-on-langchain.mdx

This PR introduces the ability to use LangChain with privately deployed Cohere models across various integrations. The updates include instructions and code examples for specifying a model deployment URL using the base_url parameter in the following files:
- chat-on-langchain.mdx
- embed-on-langchain.mdx
- rerank-on-langchain.mdx

Add snippets for using langchain on private deployments

---

fern/pages/going-to-production/rate-limits.mdx

This pull request updates the rate limits for the Cohere API keys. The changes are as follows:
- The rate limit for the **Embed (Images)** API key has been increased from **40/min** to **400/min**.

Image embed limit

---

fern/pages/text-generation/prompt-engineering/command-r7b-hf.mdx

This pull request introduces a new feature to the application, allowing users to create and manage their own profiles. The changes include the addition of a new `Profile` model, modifications to the `User` model, and updates to the `views.py` file to handle profile-related operations.
- **New `Profile` Model:**
- A new `Profile` model is introduced to store user profile information.
- It includes fields such as `bio`, `location`, and `birthdate`.
- The `User` model is updated to have a one-to-one relationship with the `Profile` model.
- **Updated `User` Model:**
- The `User` model now includes a `profile` field, which is a foreign key to the `Profile` model.
- This change enables users to have a single profile associated with their account.
- **Modified `views.py`:**
- The `views.py` file …

Update cmd r7b usage docs

---

fern/pages/fine-tuning/fine-tuning-with-the-python-sdk.mdx
fern/pages/get-started/datasets.mdx
fern/pages/text-embeddings/embed-jobs-api.mdx
fern/pages/text-embeddings/embeddings.mdx
fern/pages/text-embeddings/multimodal-embeddings.mdx
fern/pages/text-embeddings/semantic-search-embed.mdx
fern/pages/text-embeddings/text-classification-1.mdx
fern/pages/text-embeddings/text-classification-with-cohere.mdx

In scope of this PR we apply auto-formatter rules to the python code snippets on the pages from text-embeddings section

Reformat python code snippets for text-embeddings pages

---

fern/pages/v2/text-generation/retrieval-augmented-generation-rag.mdx

This PR removes the following lines of code:
```
response = co.chat_stream(
model="command-r-plus-08-2024",
messages=messages,
documents=documents,
citation_options={"mode":"accurate"}
)
messages = [{"role": "user", "content": "Where do the tallest penguins live?"}]
```
The PR removes the code that sets the `response` variable to the result of the `co.chat_stream` function. This function is used to generate a response to a user's message, and the removed code sets the model, messages, documents, and citation options for the function.
- The `response` variable is no longer set to the result of the `co.chat_stream` function.
- The `messages` variable is no longer set to a list containing a user message.

Fix duplicate code in RAG page

---

fern/pages/cohere-api/teams-and-roles.mdx

This pull request introduces changes to the permissions and capabilities of users and owners within the system. The modifications aim to enhance security and streamline the process of managing API keys, particularly production API keys.
- **Users**:
- Can now `make` and `view` production API keys, with a note that production keys are only viewable in their entirety when they're created.
- The note regarding viewing production API keys has been updated to clarify that users can always see which keys exist.
- **Owners**:
- After completing the "Go to Production" form and receiving approval, owners or users on their team can create any number of production keys.

Changing on-page teams and roles copy.

---

fern/pages/v2/tutorials/build-things-with-cohere/building-a-chatbot-with-cohere.mdx
fern/pages/v2/tutorials/build-things-with-cohere/building-an-agent-with-cohere.mdx
fern/pages/v2/tutorials/build-things-with-cohere/rag-with-cohere.mdx
fern/pages/v2/tutorials/build-things-with-cohere/reranking-with-cohere.mdx
fern/pages/v2/tutorials/build-things-with-cohere/semantic-search-with-cohere.mdx
fern/pages/v2/tutorials/build-things-with-cohere/text-generation-tutorial.mdx

This pull request updates the links to the Colab notebooks for several tutorials.
- The link to the notebook for the tutorial on building a chatbot with Cohere has been updated to `https://colab.research.google.com/github/cohere-ai/cohere-developer-experience/blob/main/notebooks/guides/getting-started/v2/tutorial_pt3_v2.ipynb`.
- The link to the notebook for the tutorial on building an agent with Cohere has been updated to `https://colab.research.google.com/github/cohere-ai/cohere-developer-experience/blob/main/notebooks/guides/getting-started/v2/tutorial_pt7_v2.ipynb`.
- The link to the notebook for the tutorial on RAG with Cohere has been updated to `https://colab.research.google.com/github/cohere-ai/cohere-developer-experience/blob/main/notebooks/guides/getting-started/v2/tutorial_pt6_v …

Update colab links

---

fern/pages/text-embeddings/reranking/overview.mdx
fern/pages/v2/text-embeddings/reranking/overview.mdx

This PR updates the documentation for Cohere's Rerank models, specifically the `rerank-v3.5` and `rerank-multilingual-v3.0` models, to reflect their expanded language support.
- The documentation now states that the Rerank models have been trained for performance across 100+ languages.
- It provides guidance on choosing the appropriate model, highlighting the availability of separate English-only and multilingual models for Rerank 3.0 and a single multilingual model for Rerank 3.5.
- A table is added to list the supported languages, with an ISO code and language name for each.

Add rerank multilingual usage clarification

---

fern/pages/tutorials/build-things-with-cohere/reranking-with-cohere.mdx
fern/pages/v2/tutorials/build-things-with-cohere/reranking-with-cohere.mdx
notebooks/guides/getting-started/tutorial_pt5.ipynb
notebooks/guides/getting-started/v2/tutorial_pt5_v2.ipynb

This PR introduces changes to the reranking tutorial, focusing on improving search quality and supporting multilingual search.
- **Reranking Definition:** The definition of reranking has been updated to emphasize its role in providing a semantic boost to search quality for keyword and vector search systems.
- **Model Version:** The model version used for reranking has been updated from `'rerank-english-v3.0' to `'rerank-v3.5'` in various code blocks.
- **Data Conversion:** The process of performing reranking over semi-structured data has been modified. Instead of using the `rank_fields` parameter, the documents are now converted to YAML format before being passed to the Rerank endpoint.
- **Top Results:** The `top_n` parameter has been adjusted to return a single top result (`top_n=1`) …

Update getting started tutorial on reranking - removed rank fields

---

fern/pages/v2/models/the-command-family-of-models/command-beta.mdx
fern/pages/v2/models/the-command-family-of-models/command-r-plus.mdx
fern/pages/v2/models/the-command-family-of-models/command-r.mdx

Applying `black` auto-formatting to pages in `models` section.

Reformat models code samples

---

fern/pages/v2/deployment-options/cohere-on-aws/amazon-bedrock.mdx
fern/pages/v2/deployment-options/cohere-on-aws/amazon-sagemaker-setup-guide.mdx
fern/pages/v2/deployment-options/cohere-on-microsoft-azure.mdx
fern/pages/v2/deployment-options/cohere-works-everywhere.mdx

Apply `black` formatter to `deployment options` pages

Reformat deployment-options pages

---

fern/pages/llm-university/intro-text-generation/building-a-chatbot.mdx
fern/pages/llm-university/intro-text-generation/creating-custom-models.mdx
fern/pages/llm-university/intro-text-generation/fine-tuning-for-chat.mdx
fern/pages/llm-university/intro-text-generation/parameters-for-controlling-outputs.mdx
fern/pages/llm-university/intro-text-generation/prompt-engineering-basics.mdx
fern/pages/llm-university/intro-text-generation/the-generate-endpoint.mdx

Reformat code examples on `LLM university` `text-generation` section

Reformat code samples on llm university text-generation section

---

.github/workflows/create-sdk-releases.yml
.github/workflows/release-sdks.yaml
packages/autorelease/src/create-releases.ts

This pull request introduces changes to the release creation process, primarily focusing on the `create-sdk-releases.yml` and `create-releases.ts` files. The modifications aim to enhance the release workflow by adding a new trigger mechanism and refining the release creation logic.
- A new trigger mechanism is added to the release workflow, enabling releases upon a `push` event.
- The `languages` array is updated to include only "python", "typescript", and "go", removing the duplicate "typescript" entry.
- The `createRelease` function now uses a new `tagName` variable, which is formatted using the `formatTagName` function.
- The `createRelease` function is called with the "all" language, ensuring releases for all languages.
- The `bumpType` is set to "patch" for the release, indicating a …

Fix create release

---

.github/workflows/create-sdk-releases.yml

This pull request introduces a new variable, `LANGUAGE`, to the `create-sdk-releases.yml` file. The variable is set to `${{ github.event.inputs.language }}`, indicating that it will be populated with the language input provided during the GitHub event.
- Adds the `LANGUAGE` variable to the job configuration.
- The `run` command now includes the `LANGUAGE` variable, ensuring that the language input is considered during the release process.

Add language env variable

---

fern/pages/llm-university/intro-semantic-search/deeper-semantic-search.mdx
fern/pages/llm-university/intro-semantic-search/fine-tuning-for-rerank.mdx
fern/pages/llm-university/intro-semantic-search/generating-answers.mdx
fern/pages/llm-university/intro-semantic-search/keyword-search.mdx
fern/pages/llm-university/intro-semantic-search/multilingual-movie-search.mdx
fern/pages/llm-university/intro-semantic-search/reranking-2.mdx

Applying `black` formatting to LLM University "Semantch Search" section.

Reformat code examples for semantic search intro section

---

fern/pages/v2/tutorials/agentic-rag.mdx
fern/pages/v2/tutorials/agentic-rag/generating-parallel-queries.mdx
fern/pages/v2/tutorials/agentic-rag/performing-tasks-sequentially.mdx
fern/pages/v2/tutorials/build-things-with-cohere.mdx
fern/pages/v2/tutorials/build-things-with-cohere/building-an-agent-with-cohere.mdx
fern/pages/v2/tutorials/build-things-with-cohere/rag-with-cohere.mdx
fern/pages/v2/tutorials/build-things-with-cohere/reranking-with-cohere.mdx
fern/pages/v2/tutorials/build-things-with-cohere/semantic-search-with-cohere.mdx
fern/pages/v2/tutorials/cookbooks.mdx

Updating page titles to be in range between 30-60 chars to fit SEO requirements

Update page titles to fit seo requirements

---

fern/pages/text-embeddings/embeddings.mdx
fern/pages/v2/text-embeddings/embeddings.mdx

This pull request updates the documentation for the Cohere embedding platform's support for image embeddings in the `embed-v3.0` family. The changes include:
- Expanding the supported image file types to include `png`, `jpeg`, `webp`, and `gif`, with a maximum file size of 5 MB.
- Clarifying that the image must be base64 encoded and sent as a Data URL to the `images` parameter.
- Emphasizing that the `texts` field must be empty when `input_type` is set to `image`.

Multi modal image types

---

fern/pages/changelog/2025-01-24-multimodal-on-bedrock.mdx
fern/pages/deployment-options/cohere-on-aws/amazon-bedrock.mdx
fern/pages/v2/deployment-options/cohere-on-aws/amazon-bedrock.mdx

This pull request announces the release of Cohere's multimodal embedding models, which can now process images in addition to text. The models are available through the Cohere API and the Amazon Bedrock cloud computing platform.
- Added a new file `fern/pages/changelog/2025-01-24-multimodal-on-bedrock.mdx` with a release announcement for the ability to work with multimodal image models on the Amazon Bedrock platform.
- Updated the `fern/pages/deployment-options/cohere-on-aws/amazon-bedrock.mdx` and `fern/pages/v2/deployment-options/cohere-on-aws/amazon-bedrock.mdx` files to include a note about the release of multimodal embedding models and a link to more information.

Announcing multimodal models on Bedrock, plus docs changes.

---

fern/pages/going-to-production/going-live.mdx

At the moment [going-live page](https://docs.cohere.com/v2/docs/going-live) doesn't rendered properly so this PR should fix that.

Fix going live page

---

fern/pages/deployment-options/cohere-on-aws/amazon-sagemaker-setup-guide.mdx
fern/pages/deployment-options/deployment-options/aws-sagemaker.mdx
fern/pages/v2/deployment-options/cohere-on-aws/amazon-sagemaker-setup-guide.mdx

This PR introduces a new warning message for users working with Cohere software or model versions beyond 1.0.5 and 3.0.5, respectively. It highlights the need to specify the `InferenceAmiVersion=al2-ami-sagemaker-inference-gpu-2` parameter on the endpoint configuration to prevent deployment errors.
- **New Warning:** A warning is added to inform users about a specific configuration requirement for Cohere software and model versions above 1.0.5 and 3.0.5, respectively.
- **Configuration Requirement:** The warning emphasizes the need to set the `InferenceAmiVersion` parameter to `al2-ami-sagemaker-inference-gpu-2` on the endpoint configuration to ensure successful deployments.

Adding warning to AWS SM setup guide for version compatibility issue.

---

fern/pages/changelog/2025-01-24-multimodal-on-bedrock.mdx

This pull request updates the title of the changelog to reflect the availability of Cohere's Multimodal Embedding Models on Bedrock.
- The title is changed from "Cohere's Multimodal Embedding Models are on SageMaker!" to "Cohere's Multimodal Embedding Models are on Bedrock!".

Fixing the title.

---

fern/pages/going-to-production/how-does-cohere-pricing-work.mdx

This PR introduces a new section titled "What's the Difference Between 'billed' Tokens and Generic Tokens?" to clarify the distinction between billed and generic tokens in the JSON output.
- Added a new section to explain the difference between billed and generic tokens.
- Included a JSON example to illustrate the difference in input and output values under `billed_units` and `tokens`.
- Clarified that billed tokens are the ones users are charged for, while generic tokens may include additional tokens added by Cohere or the model, which users are not charged for.

Explaining billed tokens and why they're different.

---

fern/pages/tutorials/cohere-on-azure/azure-ai-rag.mdx
fern/pages/v2/tutorials/cohere-on-azure/azure-ai-rag.mdx

There was an issue reported related to duplicates titles.
`Retrieval Augmented Generation (RAG)` is already set for `docs/retrieval-augmented-generation-rag`

Fix issue with duplicates titles

---

package.json
pnpm-lock.yaml

This PR updates the `fern-api` package to version `0.51.36` in both the `package.json` and `pnpm-lock.yaml` files.
- In `package.json`, the `fern-api` dependency is updated from `^0.41.16` to `^0.51.36`.
- In `pnpm-lock.yaml`, the `fern-api` specifier and version are updated from `^0.41.16` to `^0.51.36`, and the `fern-api@0.41.16` resolution is replaced with `fern-api@0.51.36`.

chore(docs): bump fern cli to 0.51.x

---

fern/pages/deployment-options/cohere-on-microsoft-azure.mdx
fern/pages/v2/deployment-options/cohere-on-microsoft-azure.mdx

This pull request updates the list of regions where the pay-as-you-go deployment offering is available for Cohere models in Azure AI Studio.
- The list of regions has been expanded to include `East US`, `East US 2`, `North Central US`, `South Central US`, `West US`, and `West US 3`.

Azure region updates.

---

fern/docs.yml

This PR updates the destination of a redirect in the `docs.yml` file.
- The destination of the redirect with the source `/v2/docs/implementing-a-multi-step-agent-with-langchain` is changed from `/v2/docs/tool-use-usage-patterns/multi-step-tool-use` to `/v2/docs/tool-use-usage-patterns#multi-step-tool-use`.

Tool use - fix broken redirect link

---

fern/pages/v2/get-started/quickstart/rag-quickstart.mdx
fern/pages/v2/get-started/quickstart/reranking-quickstart.mdx
fern/pages/v2/get-started/quickstart/sem-search-quickstart.mdx
fern/pages/v2/get-started/quickstart/text-gen-quickstart.mdx
fern/pages/v2/get-started/quickstart/tool-use-quickstart.mdx

I found that according to our standart `v2` path entry should goes before `docs`.

Fixing slugs for quickstart pages

---

fern/pages/fine-tuning/chat-fine-tuning/chat-starting-the-training.mdx
fern/pages/fine-tuning/classify-fine-tuning/classify-starting-the-training.mdx
fern/pages/fine-tuning/fine-tuning-with-the-cohere-dashboard.mdx
fern/pages/fine-tuning/rerank-fine-tuning/rerank-starting-the-training.mdx
fern/pages/v2/fine-tuning/chat-fine-tuning/chat-starting-the-training.mdx
fern/pages/v2/fine-tuning/classify-fine-tuning/classify-starting-the-training.mdx
fern/pages/v2/fine-tuning/rerank-fine-tuning/rerank-starting-the-training.mdx

We have warnings reported that we use http urls on the https pages.
This PR aims to fix that warnings and replace `http` with `https`

use https urls instead of http

---

fern/pages/deployment-options/north-eap-private-deployment.mdx

This PR makes changes to the installation process for a POC install.
- The `helm.cohere.com` domain is now only required during installation, but not in the cluster's firewall.
- The `api.cohere.com` domain is now only required if using the Cohere platform as the model provider.
- The `global.config.postgres.tls.caCerts.secretName` and `global.config.postgres.tls.caCerts.secretKey` flags have been removed from the installation command.
- The `global.config.redis.host`, `global.config.redis.tls.caCerts.secretName`, and `global.config.redis.tls.caCerts.secretKey` flags have also been removed from the installation command.
- The `global.config.redis.scheme` and `global.config.redis.connectionOptions` flags have been updated to use the `rediss` scheme and connection options.
- The …

docs: fix north eap docs yaml blocks

---

fern/pages/v2/text-generation/compatibility-api.mdx

This pull request updates the documentation for the Compatibility API, which allows developers to use Cohere's models through OpenAI. The changes include:
- Adding a list of supported libraries: TypeScript / JavaScript, Python, .NET, Java (beta), and Go (beta).
- Removing the `user` parameter from the unsupported parameters list.
- Adding a new section for Cohere-specific parameters, which are not supported on the OpenAI SDK. This section includes parameters for the chat and embed endpoints, with links to the Cohere documentation for more information.

Compatibility api clarification

---

fern/pages/cookbooks/aya_vision_intro.mdx

This pull request updates the image source paths in the `fern/pages/cookbooks/aya_vision_intro.mdx` file.
- The image source paths are changed from `tree/main/notebooks/images/aya-vision/` to `raw/main/notebooks/images/aya-vision/`.
- This ensures that the images are directly accessible from the raw file path, rather than being nested within the main directory.
- The change affects all image sources in the file, including the Aya Vision logo and other images used in the notebook.

Fix image links for Aya Vision cookbook

---

fern/pages/cookbooks/aya_vision_intro.mdx

This PR updates the Aya Vision documentation to reflect the new location of the Aya Vision introduction notebook.
- The `href` attribute in the `CookbookHeader` component is updated to point to the new location of the notebook.
- The markdown link to the notebook in the `.ipynb` file is also updated to reflect the new location.

Aya Vision - update cookbook links

---

fern/assets/input.css

Update color for "Learn more" text in annoucements section
Previous [PR](https://github.com/cohere-ai/cohere-developer-experience/pull/439) didn't use such precise selector and caused issue with links on the pages

Fix issue with learn more color

---

fern/pages/deployment-options/north-eap-private-deployment.mdx

This pull request updates the GPU compute requirements for a POC install.
- The GPU compute requirements have been updated to include 2x NVidia A100 or 2x NVidia H100, an increase from the previous requirement of 1x NVidia A100 or 1x NVidia H100.

Updating hardware requirements.

---

fern/pages/v2/deployment-options/private-deployment/single-container-on-private-clouds.mdx

For the Embed Multilingual example, there should be a space between `--name multilingual` and `--gpus=1`

Added necessary space between `--name multilingual` and `--gpus=1`

---

fern/pages/models/the-command-family-of-models/command-r-plus.mdx
fern/pages/v2/models/the-command-family-of-models/command-r-plus.mdx

This pull request removes the following text from the Command R+ model description:
> Note, however, that RAG and multi-step tool use (agents) are currently only available in English.
This change is made to both the `fern/pages/models/the-command-family-of-models/command-r-plus.mdx` and `fern/pages/v2/models/the-command-family-of-models/command-r-plus.mdx` files.
- **Reasoning:** The removed text is no longer accurate or relevant to the model's capabilities. It may have been included in the original description to highlight a limitation of the model, but this limitation has since been addressed or is no longer a significant factor in the model's performance.

Remove Multilingual warning for Cmd-R+

---

fern/pages/deployment-options/cohere-on-aws/amazon-sagemaker-setup-guide.mdx
fern/pages/v2/deployment-options/cohere-on-aws/amazon-sagemaker-setup-guide.mdx

This PR adds a warning to the Amazon Sagemaker Setup Guide in the Deployment Options section.
- Adds a warning that Cohere's embed models don't support batch transform operations.

Updating the SM page with batch transform information.

---

fern/pages/v2/text-generation/structured-outputs.mdx

This PR updates the documentation for the Structured Outputs feature, adding Command A to the list of compatible models and changing the model name in the code examples from `command-r-plus-08-2024` to `command-a-03-2025`.
- Adds Command A to the list of compatible models for Structured Outputs
- Updates the model name in the code examples from `command-r-plus-08-2024` to `command-a-03-2025`

The v2 doc was missed.

---

fern/pages/v2/text-generation/summarizing-text.mdx

This PR updates the model used for text generation in the summarizing-text.mdx file.
- The model used for text generation has been updated from `command-r-plus-08-2024` to `command-a-03-2025`.
- This change is reflected in all instances where the model is specified in the code.
- The update is applied consistently across all relevant functions, including those for generating concise summaries, one-sentence summaries, summaries in less than 10 words, and summaries as bullet points.
- The change also applies to the function that generates summaries with citations.
- The final function, which writes a short summary in bullet point form, also reflects this model update.

The v2 summarization doc was missed in the updates.

---

fern/pages/models/the-command-family-of-models/command-beta.mdx
fern/pages/models/the-command-family-of-models/command-r-plus.mdx

This PR updates the Command R+ and Command Beta documentation.
- Command R+ is no longer referred to as Cohere's newest large language model.
- Command Beta now recommends Command A instead of Command R.
- The prompt in the Command Beta documentation has been updated to be more specific.

Command a roy changes

---

fern/pages/deployment-options/north-eap-private-deployment.mdx

This PR updates the default configuration settings for the cohere and postgres sections, and adds a new singleContainer section.
- Updates the cohere API URLs to use generic names instead of specific versions.
- Changes the secretKeyRef name for postgres and redis passwords to `credentials` from `persistence-credentials`.
- Adds a new `singleContainer` section with a `model` field set to `command`.
- Updates the `existingSecret` field in the redis auth section to `credentials`.

Marwan's edits.

---

fern/pages/get-started/quickstart/reranking-quickstart.mdx
fern/pages/v2/get-started/quickstart/reranking-quickstart.mdx

This PR adds new code to the reranking-quickstart.mdx files in the fern/pages/get-started/quickstart and fern/pages/v2/get-started/quickstart directories.
- The new code adds a ```mdx wordWrap block with the following content:
```
document=None index=2 relevance_score=0.115670934
document=None index=1 relevance_score=0.01729751
```

Rerank quickstart - add sample response

---

fern/pages/get-started/frequently-asked-questions.mdx
fern/pages/integrations/llamaindex.mdx
fern/v1.yml
fern/v2.yml

This PR removes references to the Automatic Prompt Tuner, which is being deprecated. Removes page references in the v1 and v2 API, references in the FAQs, and in the Llama index examples.

refactor: Remove all references to prompt tuner

---

fern/pages/get-started/playground-overview.mdx

This PR updates the JSON mode link in the Playground Overview page.
- The JSON mode link has been updated to https://docs.cohere.com/docs/parameter-types-in-json

Updating a broken link in the playground guide.

---

fern/docs.yml

We've changed `Rerank` page slug from `rerank-2` to `rerank` in this [PR](https://github.com/cohere-ai/cohere-developer-experience/pull/501)
Now semrush reporting missing page at `/docs/rerank-2` so this should fix the issue

Set redirect for old rarank-2 slug

---

fern/pages/cookbooks/agentic-rag-mixed-data.mdx
fern/pages/cookbooks/elasticsearch-and-cohere.mdx
fern/pages/integrations/cohere-and-langchain/chat-on-langchain.mdx
fern/pages/integrations/integrations/elasticsearch-and-cohere.mdx
scripts/cookbooks-mdx/agentic-rag-mixed-data.mdx
scripts/cookbooks-mdx/elasticsearch-and-cohere.mdx

This PR updates links in the documentation to ensure they point to the most current and relevant resources.
- **fern/pages/cookbooks/agentic-rag-mixed-data.mdx**: Updated the link for LangChain-supported parsers from `https://python.langchain.com/docs/modules/data_connection/document_loaders/pdf/` to `https://python.langchain.com/docs/how_to/document_loader_pdf/`.
- **fern/pages/cookbooks/agentic-rag-mixed-data.mdx**: Updated the link for multi-vector retrieval from `https://python.langchain.com/docs/modules/data_connection/retrievers/multi_vector/` to `https://python.langchain.com/docs/how_to/multi_vector/`.
- **fern/pages/cookbooks/elasticsearch-and-cohere.mdx**: Updated the link for the `put_pipeline` method from `https://www.elastic.co/guide/en/elasticsearch/reference/master/put-pipeli …

Fix broken external urls

---

fern/pages/deployment-options/north-eap-private-deployment.mdx

This PR updates the north-eap-private-deployment.mdx file, which describes the steps required for a POC install of North.
- The image path has been updated.
- The databases required for the installation have been updated to include `openfga` and `dex` in addition to `north` and `compass`.
- The secretsGenerator section has been updated to disable default secrets and remove the `auth-secret-key` and `opensearch-password` secrets.
- The toolkit configuration has been updated to include `dex` and `openfgaService` settings.
- The ingress routes section has been updated to remove extra line breaks.
- The OIDC authentication section has been updated to improve readability and remove extra line breaks.

chore: update eap docs

---

fern/pages/v2/get-started/quickstart/text-gen-quickstart.mdx

This pull request adds a new section to the documentation, providing information about the `model` parameter definition for private deployments. The section includes a code snippet demonstrating how to use the `model` parameter with the Cohere platform.
- Added a new section with an `<Info>` tag, containing details about the `model` parameter definition for private deployments.
- Included a code snippet under the Cohere Platform tab, showing the usage of the `model` parameter.
- The code snippet prints the response message content's text using `print(response.message.content[0].text)`.

Add info about private deployment in quickstart

---

fern/docs.yml
fern/pages/changelog/2025-03-04-aya-vision-is-here.mdx
fern/pages/cohere-for-ai/c4ai-acceptable-use-policy.mdx
fern/pages/cohere-labs/cohere-labs-acceptable-use-policy.mdx
fern/pages/cookbooks/aya_vision_intro.mdx
fern/pages/llm-university/intro-text-generation/introduction-to-text-generation.mdx
fern/pages/llm-university/intro-the-cohere-platform/foundation-models.mdx
fern/pages/models/aya-expanse.mdx
fern/pages/models/aya-multimodal.mdx
fern/pages/models/aya.mdx
fern/v1.yml
fern/v2.yml

This PR updates the name of Cohere's research arm from 'Cohere For AI' to 'Cohere Labs' across the following files:
- fern/pages/changelog/2025-03-04-aya-vision-is-here.mdx
- fern/pages/cohere-for-ai/c4ai-acceptable-use-policy.mdx
- fern/pages/cookbooks/aya_vision_intro.mdx
- fern/pages/llm-university/intro-text-generation/introduction-to-text-generation.mdx
- fern/pages/llm-university/intro-the-cohere-platform/foundation-models.mdx
- fern/pages/models/aya-expanse.mdx
- fern/pages/models/aya-multimodal.mdx
- fern/pages/models/aya.mdx
- fern/v1.yml
- fern/v2.yml

Replace Cohere for AI with Cohere Labs

---

fern/pages/text-embeddings/semantic-search-embed.mdx
fern/pages/v2/text-embeddings/semantic-search-embed.mdx

This PR updates the `pdf_path` variable in the Python code and the link to the cookbook version of the multimodal PDF search example.
- The `pdf_path` variable is updated to `"PDF_FILE_PATH"` and the original path is added as a comment.
- The link to the cookbook version of the multimodal PDF search example is updated to point to the `embed-v4-pdf-search.ipynb` file.

Fix urls for notebook and file path

---

fern/pages/changelog/2025-04-15-embed-multimodal-v4.mdx

At the moment embed-4 url redirects people to `https://docs.cohere.com/cohere.com/blog/embed-4`

Fix embed-4 url

---

fern/pages/cookbooks.mdx
fern/pages/cookbooks/retrieval-eval-pydantic-ai.mdx
fern/v1.yml
fern/v2.yml
notebooks/guides/retrieval_eval_pydantic_ai.ipynb

This PR adds a tutorial on how to evaluate retrieval systems using LLMs as judges via Pydantic AI.
- Adds a new page to the Cookbooks section titled "Retrieval evaluation using LLM-as-a-judge via Pydantic AI"
- Includes a description, image, and keywords for the new page
- Imports the CookbookHeader component and adds a header linking to the GitHub repository
- Provides an overview of the tutorial's objectives and the tools used
- Adds a Setup section with instructions to import necessary libraries and install required packages
- Includes code snippets and explanations for:
- Performing a Wikipedia search
- Reranking search results using Cohere's API
- Filtering top_n results for comparison
- Implementing an LLM-as-a-judge evaluation framework
- Adds a Conclusion section summarizing the …

Add pydantic ai for retrieval cookbook

---

fern/pages/changelog/2025-04-15-embed-multimodal-v4.mdx
fern/pages/get-started/frequently-asked-questions.mdx
fern/pages/models/models.mdx

This PR updates the documentation with new links and information about the availability of Embed v4.
**Summary of Changes:**
- **Updated Links for Embed v4 Availability:**
- The links for AWS Sagemaker and Azure AI Foundry have been updated to point to their respective setup guides.
- **Updated Link for Handling PDFs with Mixed Data:**
- The link for handling PDFs with mixed data has been updated to point to the semantic search embed documentation.
- **Added Azure AI Foundry Model ID for Embed v4:**
- The Azure AI Foundry model ID for `embed-v4.0` has been added as `cohere-embed-v-4-plan`.
These changes ensure that the documentation is up-to-date and provides accurate information about the availability and usage of Embed v4.

Three fast follows.

---

fern/pages/going-to-production/deprecations.mdx

This PR updates the shutdown date for the `rerank-english-v2.0` and `rerank-multilingual-v2.0` models in the `fern/pages/going-to-production/deprecations.mdx` file.
- The shutdown date for both models has been extended from 2025-03-31 to 2025-04-30.

changed shutdown dates

---

fern/pages/text-generation/predictable-outputs.mdx
fern/pages/v2/models/the-command-family-of-models/command-beta.mdx
fern/pages/v2/text-generation/predictable-outputs.mdx

This PR updates the temperature parameter and model recommendation in the documentation.
- The temperature parameter is now defined as a value ranging from `0-1` with a default value of `.3`.
- The recommended temperature range for tasks with a "correct" answer is now `0.1` to `0.3`.
- The suggested starting point for temperature is now `0.3` or `0.5` instead of `1`.
- The recommended model for most use cases is now [Command A](https://docs.cohere.com/docs/command-a) instead of [Command R](/v2/docs/command-r).

Updated temperature values, also changed the v2 banner in command-beta.

---

notebooks/guides/Document_Parsing_For_Enterprises.ipynb

This PR updates the Document_Parsing_For_Enterprises.ipynb file by correcting the spelling of the "strategy" variable.
- The spelling of the "strategy" variable has been corrected.

Correct misspelling of "strategy" in data dictionary

---

notebooks/guides/Document_Parsing_For_Enterprises.ipynb

Adding example service endpoint to commented line
`# enter service endpoint, for example "http://localhost:9500/general/v0/general" (assuming the container is running locally and exposing the service with a -p 9500:9500 port mapping)`

provide example service endpoint for unstructured container

---

fern/pages/changelog/2022-11-03-coclassify-powered-by-our-representational-model-embeddings.mdx
fern/pages/changelog/2022-11-08-improvements-to-current-models-new-beta-model-command.mdx
fern/pages/changelog/2022-12-12-multilingual-text-understanding-model-language-detection.mdx
fern/pages/changelog/2025-01-31-classify-default-model-deprecation.mdx
fern/pages/changelog/2025-02-26-compatibility-api.mdx
fern/pages/cookbooks/article-recommender-with-text-embeddings.mdx
fern/pages/cookbooks/migrate-csv-agent.mdx
fern/v2.yml

This PR should fix long titles reported by SemRush.
For some titles we add either `- cohere` or `(v1 API) — Cohere` which make titles longer than max limit 70 chars

Fix too long titles

---

fern/v1.yml
fern/v2.yml

Currently if we visit docs.cohere.com we redirected automatically to docs.cohere.com/cohere-documentation
This PR should fix that and we should get page docs.cohere.com without any redirects.
on preview app it looks ok

Remove redirect for docs homepage

---

fern/pages/v2/text-generation/compatibility-api.mdx

we now support logprogs, max_completion_tokens, and stream_options

chore: update compat api unsupported params

---

fern/pages/deployment-options/single-container-on-private-clouds.mdx
fern/pages/v2/deployment-options/private-deployment/single-container-on-private-clouds.mdx

This PR updates the number of GPUs used for the command in the `docker run` command and environment variable configuration.
- Reduces the number of GPUs from 4 to 2 in the `docker run` command for the `command` container.
- Adds a comment indicating that the number of GPUs may vary depending on the target model.
- Updates the `GPUS` environment variable to accept a dynamic value representing the number of GPUs required for the target model, instead of a fixed value of 4.

Update figures 

---

fern/pages/v2/text-generation/tokens-and-tokenizers.mdx

This PR updates the API client initialization in the Cohere Tokenizers code examples.
- `cohere.ClientV2(api_key="YOUR API KEY")` is replaced with `cohere.Client(api_key="YOUR API KEY")` in both code snippets.

chore: tokenize/detokenize only available in v1

---

fern/pages/deployment-options/single-container-on-private-clouds.mdx

**Description**
The single-container-on-private-clouds.mdx file has been updated to clarify the scope of the license for air-gapped workflows.
**Changes**
- Clarifies that the image can be re-tagged and replicated within the scope of the license for air-gapped workflows.

Update wording for licensed usage

---

fern/pages/changelog/2025-09-16-announcing-major-command-deprecations.mdx
fern/pages/going-to-production/deprecations.mdx

This PR introduces a new changelog entry and updates the existing deprecation history with the following changes:
- Deprecates the `command-light` and `command` models, recommending alternatives like `command-r-08-2024` and `command-a-03-2025` for `command-light`, and `command-r-03-2024` or `command-r-plus-04-2024` for `command`.
- Retires fine-tuning capabilities for models including `command-light`, `command`, `command-r`, `classify`, and `rerank`, making previously fine-tuned models inaccessible.
- Deprecates several API endpoints and features, including:
- `/v1/connectors` (Managed connectors for RAG)
- `/v1/chat` parameters: `connectors`, `search_queries_only`
- `/v1/generate` (Legacy generative endpoint)
- `/v1/summarize` (Legacy summarization endpoint)
- `/v1/classify`
- Slack App …

Sep 2025 deprecation changelog

---

fern/v1.yml
fern/v2.yml

This PR reorders the navigation structure in the `fern/v1.yml` and `fern/v2.yml` files.
- `Command A Translate` is moved above `Command A Reasoning` and `Command A Vision` in both files.
- `Command R7B` is moved below `Command A Vision` in both files.

Reorder models in navigation

---

fern/components/model-showcase.tsx

**Description**
This PR updates the `model-showcase.tsx` file to provide clearer information about rate limits for different models and key types.
**Changes**
- The text `{model.name} is available for free trial usage up to rate limits.` has been replaced with `For both trial keys and production keys, {model.name} is free until rate limits are reached. Learn more about rate limits for different models and key types here.`.
- A hyperlink has been added to the text `here` which links to `https://docs.cohere.com/docs/rate-limits`.
- The text `For production usage, please reach out to sales at` has been replaced with `To use {model.name} in production, please reach out to sales at`.

Update pricing text for command a models
