fern/v1.yml

`Chat Non-Streaming` -> `Chat`
`Chat Streaming` -> `Chat with Streaming`
`Generate Non-Streaming` -> `Generate`
`Generate Streaming` -> `Generate with Streaming`

Update the names of the Chat API headings

---

fern/pages/cookbooks/basic-tool-use.mdx
fern/pages/cookbooks/calendar-agent.mdx
fern/pages/text-generation/prompt-engineering/prompt-tuner.mdx
fern/pages/tutorials/build-things-with-cohere.mdx

[GRO-2052](https://linear.app/cohereai/issue/GRO-2052/7-pages-have-duplicate-meta-descriptions)

(docs)duplicated description issue

---

fern/docs.yml
fern/pages/index.mdx

Reverts cohere-ai/cohere-developer-experience#32

Revert "disable dark mode"

---

fern/pages/cookbooks.mdx

[GRO-2083](https://linear.app/cohereai/issue/GRO-2083/update-documentation-for-cookbooks-to-correct-discrepancy)

(docs)Cookbook - navbar item fix

---

fern/pages/cohere-api/about.mdx
fern/pages/responsible-use/environmental-impact.mdx
fern/pages/responsible-use/responsible-use.mdx
fern/pages/responsible-use/responsible-use/data-statement.mdx
fern/pages/responsible-use/responsible-use/generation-benchmarks.mdx
fern/pages/responsible-use/responsible-use/model-limitations.mdx
fern/pages/responsible-use/responsible-use/representation-benchmarks.mdx
fern/pages/responsible-use/responsible-use/usage-guidelines.mdx
fern/v1.yml
fern/v2.yml

[GRO-2084](https://linear.app/cohereai/issue/GRO-2084/take-down-inaccurate-pages-causing-confusion)

(docs)Hide Responsible Use

---

fern/pages/deployment-options/cohere-works-everywhere.mdx

[GRO-2099](https://linear.app/cohereai/issue/GRO-2099/update-rerank-status-to-checked-on-azure-feature-support-table)

Rerank Azure ✅

---

fern/docs.yml
fern/fern.config.json
pnpm-lock.yaml

[GRO-2102](https://linear.app/cohereai/issue/GRO-2102/change-temporary-redirects-to-permanent-on-fern)

(docs)Temporary redirects to permanent

---

cohere-openapi.yaml
fern/docs.yml
fern/pages/api-reference/connectors-1/delete-connector.mdx
fern/pages/api-reference/connectors-1/get-connector.mdx
fern/pages/changelog/2022-08-05-introducing-moderate-beta.mdx
fern/pages/changelog/2023-09-27-release-notes-september-29th-2023.mdx
fern/pages/changelog/2024-01-02-release-notes-january-x-2024.mdx
fern/pages/changelog/2024-06-10-release-notes-for-june-10th-2024.mdx
fern/pages/changelog/release-notes.mdx
fern/pages/deployment-options/getting-started-with-coral-toolkit.mdx
fern/pages/fine-tuning/chat-fine-tuning/chat-starting-the-training.mdx
fern/pages/get-started/the-cohere-platform.mdx
fern/pages/integrations/cohere-and-langchain/chat-on-langchain.mdx
fern/pages/integrations/integrations/haystack-and-cohere.mdx
fern/pages/llm-university/intro-text-representation/clustering-using-embeddings.mdx
fern/pages/llm-university/intro-text-representation/introduction-to-semantic-search.mdx
fern/pages/llm-university/intro-text-representation/semantic-search-using-embeddings.mdx
fern/pages/text-embeddings/embeddings.mdx
fern/pages/text-generation/retrieval-augmented-generation-rag.mdx
fern/pages/tutorials/cookbooks.mdx

[GRO-2109](https://linear.app/cohereai/issue/GRO-2109/broken-links-in-docs)

(docs)Remove broken links

---

fern/docs.yml

[GRO-2140](https://linear.app/cohereai/issue/GRO-2140/redirect-to-usage-guidelines)

(docs)Redirects to usage-guidelines

---

fern/pages/api-reference/finetuning-1/createfinetunedmodel.mdx
fern/pages/models/cohere-embed.mdx
fern/pages/models/rerank-2.mdx
fern/pages/models/the-command-family-of-models/command-r-plus.mdx
fern/pages/models/the-command-family-of-models/command-r.mdx
fern/pages/tutorials/cookbooks.mdx

[GRO-2144](https://linear.app/cohereai/issue/GRO-2144/update-5-duplicate-page-titles-for-better-seo)

(docs)Duplicated titles

---

cohere-openapi.yaml

[GRO-2144](https://linear.app/cohereai/issue/GRO-2144/update-5-duplicate-page-titles-for-better-seo)

(docs)Update chat api description

---

fern/pages/fine-tuning/fine-tuning-with-the-cohere-dashboard.mdx
fern/pages/fine-tuning/fine-tuning-with-the-python-sdk.mdx

[GRO-2152](https://linear.app/cohereai/issue/GRO-2152/links-to-redirect-chains)

(docs)links to redirect chains fix

---

.github/workflows/preview-docs.yml

Reverts cohere-ai/cohere-developer-experience#143

Revert "Update preview-docs.yml"

---

fern/pages/integrations/cohere-and-langchain/tools-on-langchain.mdx
fern/pages/integrations/integrations/elasticsearch-and-cohere.mdx
fern/pages/text-generation/chat-api.mdx
fern/pages/text-generation/connectors/overview-1.mdx
fern/pages/text-generation/predictable-outputs.mdx
fern/pages/text-generation/prompt-engineering/advanced-prompt-engineering-techniques.mdx
fern/pages/text-generation/prompt-engineering/crafting-effective-prompts.mdx
fern/pages/text-generation/prompt-engineering/preambles.mdx
fern/pages/text-generation/retrieval-augmented-generation-rag.mdx
fern/pages/text-generation/structured-outputs-json.mdx
fern/pages/text-generation/summarizing-text.mdx
fern/pages/text-generation/tokens-and-tokenizers.mdx
fern/pages/text-generation/tools/multi-step-tool-use.mdx
fern/pages/text-generation/tools/multi-step-tool-use/implementing-a-multi-step-agent-with-langchain.mdx
fern/pages/text-generation/tools/single-step-vs-multi-step.mdx
fern/pages/text-generation/tools/tool-use.mdx
fern/pages/tutorials/build-things-with-cohere/building-an-agent-with-cohere.mdx
fern/pages/tutorials/build-things-with-cohere/rag-with-cohere.mdx
fern/pages/tutorials/build-things-with-cohere/text-generation-tutorial.mdx

Update command model to latest versions
- command-r to command-r-08-2024
- command-r-plus to command-r-plus-08-2024

Update command model to latest versions

---

fern/pages/changelog/2023-06-28-release-notes-june-28th-2023.mdx
fern/pages/cookbooks/article-recommender-with-text-embeddings.mdx
fern/pages/fine-tuning/fine-tuning-with-the-python-sdk.mdx
fern/pages/fine-tuning/fine-tuning.mdx
fern/pages/text-generation/tools/multi-step-tool-use/implementing-a-multi-step-agent-with-langchain.mdx

This pull request updates various aspects of the documentation, including links, code snippets, and references to Cohere's products and services.
- **fern/pages/changelog/2023-06-28-release-notes-june-28th-2023.mdx:** Updates the link to the Cohere dashboard for the usage and billing table, ensuring it points to the correct location.
- **fern/pages/cookbooks/article-recommender-with-text-embeddings.mdx:** Modifies the link to the Cohere Classify endpoint, providing the correct reference for building a news category classifier.
- **fern/pages/fine-tuning/fine-tuning-with-the-python-sdk.mdx:** Adjusts the link to the Cohere Playground, ensuring users can access the correct location to try out their fine-tuned models.
- **fern/pages/fine-tuning/fine-tuning.mdx:** Updates the link to the …

Fixing some broken links.

---

fern/pages/cohere-api/about.mdx
fern/pages/fine-tuning/classify-fine-tuning/classify-starting-the-training.mdx
fern/pages/models/the-command-family-of-models/command-r-plus.mdx
fern/pages/models/the-command-family-of-models/command-r.mdx

Fixing a bunch of duplicate tags.

Fixing some duplicate title tags.

---

fern/pages/cohere-api/about.mdx

Update about page for v2 snippets

---

fern/pages/changelog/2024-09-26-api-v2.mdx
fern/pages/get-started/the-cohere-platform.mdx

previously the release note for v2 was 9/18, changed to make it 9/26

changed the release note date to reflect actual release date

---

fern/docs.yml
fern/pages/changelog/2024-01-02-release-notes-january-x-2024.mdx
fern/pages/text-generation/connectors/connector-faqs.mdx
fern/pages/text-generation/retrieval-augmented-generation-rag.mdx
fern/pages/v2/text-embeddings/embeddings.mdx
fern/pages/v2/text-generation/migrating-v1-to-v2.mdx
fern/pages/v2/text-generation/prompt-engineering/preambles.mdx
fern/pages/v2/tutorials/build-things-with-cohere/rag-with-cohere.mdx

I had to update a few more broken links.

V1 default

---

fern/pages/cohere-api/errors.mdx

This pull request introduces a comprehensive list of HTTP status codes and their corresponding error messages for the Cohere API. The changes aim to provide developers with a clear understanding of potential issues and how to resolve them.
- **400 - Bad Request**: Sent when the request body is invalid due to missing or incorrect fields. Developers should consult the API spec to ensure they provide the correct fields and values.
- **401 - Unauthorized**: Occurs when the API key is missing, invalid, or expired. Developers should ensure they provide a valid API key.
- **402 - Payment Required**: Indicates that the account has reached its billing limit. Developers need to add or update their payment method.
- **404 - Not Found**: Sent when the requested resource is not found, possibly due to …

Update error codes

---

fern/pages/v2/tutorials/agentic-rag/generating-parallel-queries.mdx
fern/pages/v2/tutorials/agentic-rag/performing-tasks-sequentially.mdx
fern/pages/v2/tutorials/agentic-rag/routing-queries-to-data-sources.mdx

This pull request introduces several changes to the tutorial on agentic RAG, focusing on query handling, tool setup, and sequential reasoning.
- **Query Handling**: The tutorial now emphasises the importance of query expansion and splitting for complex queries, especially in multi-turn conversations. It provides an example of how the `run_agent` function handles multi-turn conversations by appending messages to the `messages` list.
- **Tool Setup**: The tutorial clarifies the setup process for tools in an agentic RAG system. It defines a Python function for each tool, mapping them to a dictionary called `functions_map` for easy access. The tool schemas are defined with fields like `name`, `description`, and `parameters`, enabling the LLM to make informed tool call decisions.
- …

Agentic RAG tutorials - fix typos and others

---

fern/pages/integrations/cohere-and-langchain/tools-on-langchain.mdx

Update single step tool use using Langchain.

Update single step Langchain

---

fern/pages/integrations/cohere-and-langchain/chat-on-langchain.mdx
fern/pages/v2/text-generation/tools/tool-use.mdx
fern/pages/v2/tutorials/agentic-rag.mdx
fern/pages/v2/tutorials/agentic-rag/generating-parallel-queries.mdx
fern/pages/v2/tutorials/agentic-rag/performing-tasks-sequentially.mdx
fern/pages/v2/tutorials/agentic-rag/routing-queries-to-data-sources.mdx

This PR introduces updates to the documentation for Cohere's Command R family of models, focusing on tool use and Retrieval Augmented Generation (RAG) techniques. The changes aim to provide clearer and more comprehensive explanations of these concepts, along with practical examples and tutorials.
- **Tool Use:** The section on tool use has been enhanced to explain how it enables a richer set of behaviors by leveraging data from various sources. It highlights the value for enterprise developers and provides examples of new use cases, such as interacting with a CRM or conducting data science analysis.
- **RAG with LangChain:** The documentation now includes a link to the Cohere's RAG documentation, ensuring users have access to the latest and most accurate information.
- **Agentic RAG …

Language updates

---

fern/pages/text-embeddings/semantic-search-embed.mdx
fern/pages/v2/text-embeddings/semantic-search-embed.mdx
fern/v1.yml
fern/v2.yml

Add docs on semantic search in the text embeddings section.
Includes v1 and v2 pages.

Add docs on semantic search

---

fern/pages/llm-university/intro-text-representation/clustering-with-embeddings.mdx

This pull request makes a small but significant change to the text of a Markdown file.
- The heading "Step 1: Embed the Text for Clustering" has been corrected to fix a typo.

Fix spelling

---

fern/pages/v2/tutorials/agentic-rag/generating-parallel-queries.mdx
fern/pages/v2/tutorials/agentic-rag/performing-tasks-sequentially.mdx
fern/pages/v2/tutorials/agentic-rag/routing-queries-to-data-sources.mdx

Agentic rag tutorials - add note to import tool defs.

Agentic rag tutorials - add note to import tool defs

---

fern/pages/text-embeddings/embeddings.mdx
fern/pages/v2/text-embeddings/embeddings.mdx
fern/pages/v2/text-embeddings/multimodal-embeddings.mdx
fern/v2.yml

- Fixed broken links and improved formatting
- Added PIL and BytesIO imports for image processing
- v2 - Added new multimodal embeddings documentation page
- v2 - Updated embeddings documentation with image embedding capabilities
- Fixed navigation paths in v2.yml

Update embeddings docs

---

fern/pages/v2/text-embeddings/semantic-search-embed.mdx
fern/v1.yml
fern/v2.yml

- Added semantic search documentation to navigation in both v1 and v2 paths
- v2 - update from cohere.Client to cohere.ClientV2

Add semantic search docs

---

fern/pages/deployment-options/cohere-on-microsoft-azure.mdx

This PR updates the user's question in the `data` object from "What is good about Wuhan?" to "What is an LLM?".
- The `role` of the user is now to ask about LLMs.

Update azure example

---

fern/pages/cohere-api/about.mdx
fern/pages/get-started/datasets.mdx

This PR doesn't contain any source code changes, it contains only black-reformatter changes for code snippets.
I set max-length = 70 charachters to remove horizontal scrolling on code snippets.

Black code snippets on about page and Get Started section pages

---

fern/pages/deployment-options/single-container-on-private-clouds.mdx

Tiny change to add url to nvidia driver urls

Add nvidia drivers url to deployments section

---

fern/pages/v2/tutorials/agentic-rag/generating-multi-faceted-queries.mdx

Apply formatting by `black`. No code changes have been implemented

Reformat code samples for generic rag section

---

fern/pages/cookbooks/convfinqa-finetuning-wandb.mdx
fern/pages/cookbooks/deploy-finetuned-model-aws-marketplace.mdx
fern/pages/cookbooks/finetune-on-sagemaker.mdx
fern/pages/cookbooks/rag-cohere-mongodb.mdx

Apply black formatting to cookbooks section, no code-changes have been done.

Reformat code samples for cookbooks

---

fern/pages/cookbooks.mdx
fern/pages/cookbooks/sql-agent-cohere-langchain.mdx
fern/v1.yml
fern/v2.yml

Adds a new cookbook tutorial demonstrating how to build a SQL agent using Cohere and LangChain for natural language database querying in a manufacturing context.

Add sql agent with cohere and langchain cookbook

---

package.json

Reverts cohere-ai/cohere-developer-experience#272

Revert "Update package.json to upgrade Fern"

---

fern/pages/v2/deployment-options/cohere-on-aws/amazon-bedrock.mdx

Document Rerank on the Bedrock guide

---

fern/pages/text-generation/prompt-engineering/command-r7b-hf.mdx

This pull request introduces a new feature to the application, allowing users to create and manage their own profiles. The changes are primarily focused on the user profile functionality, with updates to the database schema, API endpoints, and the user interface.
- **Database Schema:**
- A new `User` model is added to the database schema, representing user profiles.
- The `User` model includes fields for user-specific information such as `username`, `email`, `password`, and `profile_picture`.
- The `User` model is associated with the existing `Post` model through a foreign key relationship, allowing users to create and manage posts.
- **API Endpoints:**
- New API endpoints are created to handle user profile-related operations:
- `POST /api/users/register`: Allows users to register and …

Add cmd prompt

---

fern/pages/text-generation/prompt-engineering/command-r7b-hf.mdx

Fix prompt rendering to show blank lines

Fix prompt rendering to show blank lines

---

fern/pages/v2/deployment-options/cohere-works-everywhere.mdx

This pull request updates the `cohere-works-everywhere.mdx` file, specifically the table that outlines the availability of various Cohere features across different deployment options.
The changes are as follows:
- The `rerank` feature is now available for all deployment options, including the Cohere platform.
- The `classify` and `summarize` features are now available for the Cohere platform, but not for the other deployment options.

I forgot to add it to the v2 doc as well.

---

fern/pages/text-generation/prompt-engineering/command-r7b-hf.mdx

Updates the Using Command R7B on Hugging Face page with tool use examples.

Add tool use docs - r7b

---

fern/pages/v2/fine-tuning/classify-fine-tuning/classify-starting-the-training.mdx

Update outdated classify finetuning snippets for the v2 API docs.
The updated snippets were taken from the v2 API snippets, which are up to date.

Update classify ft for v2 API

---

pyproject.toml

This PR introduces a new project named `cohere-developer-experience` in the `pyproject.toml` file.
- The `project` section is added to the file, containing the project name.
- The project name is set to `cohere-developer-experience`.

Fix poetry 2 compatibility

---

fern/pages/v2/text-generation/summarizing-text.mdx

We've noticed that at the moment code example is not really correct and contains just two same code parts.
This PR should fix code example on how to migrate from `summarize` to `chat` endpoint for summarization

Fix code example on how to migrate from summazite to chat endpoint

---

fern/pages/fine-tuning/chat-fine-tuning/chat-preparing-the-data.mdx
fern/pages/fine-tuning/chat-fine-tuning/chat-starting-the-training.mdx
fern/pages/fine-tuning/classify-fine-tuning/classify-preparing-the-data.mdx
fern/pages/fine-tuning/classify-fine-tuning/classify-starting-the-training.mdx
fern/pages/fine-tuning/rerank-fine-tuning/rerank-preparing-the-data.mdx
fern/pages/fine-tuning/rerank-fine-tuning/rerank-starting-the-training.mdx

Re-formating fine-tuning code examples using black

Re-format chat-fine-tuning code samples

---

fern/pages/text-generation/feedback.mdx
fern/pages/text-generation/predictable-outputs.mdx
fern/pages/text-generation/prompt-engineering/advanced-prompt-engineering-techniques.mdx
fern/pages/text-generation/retrieval-augmented-generation-rag.mdx

Re-formating text-generation code examples using black

reformat text-generation python code examples

---

fern/pages/v2/tutorials/agentic-rag/generating-multi-faceted-queries.mdx
fern/pages/v2/tutorials/agentic-rag/generating-parallel-queries.mdx
fern/pages/v2/tutorials/agentic-rag/performing-tasks-sequentially.mdx
fern/pages/v2/tutorials/agentic-rag/querying-structured-data-sql.mdx
fern/pages/v2/tutorials/agentic-rag/querying-structured-data-tables.mdx
fern/pages/v2/tutorials/agentic-rag/routing-queries-to-data-sources.mdx
fern/pages/v2/tutorials/build-things-with-cohere.mdx
fern/pages/v2/tutorials/build-things-with-cohere/building-a-chatbot-with-cohere.mdx
fern/pages/v2/tutorials/build-things-with-cohere/building-an-agent-with-cohere.mdx
fern/pages/v2/tutorials/build-things-with-cohere/rag-with-cohere.mdx
fern/pages/v2/tutorials/build-things-with-cohere/reranking-with-cohere.mdx
fern/pages/v2/tutorials/build-things-with-cohere/semantic-search-with-cohere.mdx
fern/pages/v2/tutorials/build-things-with-cohere/text-generation-tutorial.mdx

Applying `black` auto-formatting to pages in `tutorials` section

Apply auto-formatting for pages in tutorials section

---

fern/pages/v2/text-generation/prompt-engineering/advanced-prompt-engineering-techniques.mdx
fern/pages/v2/text-generation/prompt-engineering/crafting-effective-prompts.mdx
fern/pages/v2/text-generation/prompt-engineering/preambles.mdx
fern/pages/v2/text-generation/prompt-engineering/prompt-library/add-a-docstring-to-your-code.mdx
fern/pages/v2/text-generation/prompt-engineering/prompt-library/book-an-appointment.mdx
fern/pages/v2/text-generation/prompt-engineering/prompt-library/create-a-markdown-table-from-raw-data.mdx
fern/pages/v2/text-generation/prompt-engineering/prompt-library/create-csv-data-from-json-data.mdx
fern/pages/v2/text-generation/prompt-engineering/prompt-library/evaluate-your-llm-response.mdx
fern/pages/v2/text-generation/prompt-engineering/prompt-library/meeting-summarizer.mdx
fern/pages/v2/text-generation/prompt-engineering/prompt-library/multilingual-interpreter.mdx
fern/pages/v2/text-generation/prompt-engineering/prompt-library/remove-pii.mdx

Applying `black` auto-formatting to `prompt-engineering`  section in `text-generation`.

Reformat prompt-engineering section

---

fern/pages/v2/text-generation/chat-api.mdx
fern/pages/v2/text-generation/documents-and-citations.mdx
fern/pages/v2/text-generation/migrating-v1-to-v2.mdx
fern/pages/v2/text-generation/parameter-types-in-json.mdx
fern/pages/v2/text-generation/retrieval-augmented-generation-rag.mdx
fern/pages/v2/text-generation/safety-modes.mdx
fern/pages/v2/text-generation/streaming.mdx
fern/pages/v2/text-generation/structured-outputs.mdx
fern/pages/v2/text-generation/summarizing-text.mdx
fern/pages/v2/text-generation/tokens-and-tokenizers.mdx

Apply `black` auto-formatting to `text-generation` code snippets

reformat code examples from text-generation section

---

fern/pages/v2/fine-tuning/chat-fine-tuning/chat-preparing-the-data.mdx
fern/pages/v2/fine-tuning/chat-fine-tuning/chat-starting-the-training.mdx
fern/pages/v2/fine-tuning/classify-fine-tuning/classify-preparing-the-data.mdx
fern/pages/v2/fine-tuning/classify-fine-tuning/classify-starting-the-training.mdx
fern/pages/v2/fine-tuning/fine-tuning-with-the-python-sdk.mdx
fern/pages/v2/fine-tuning/rerank-fine-tuning/rerank-preparing-the-data.mdx
fern/pages/v2/fine-tuning/rerank-fine-tuning/rerank-starting-the-training.mdx

Appliying `black` formatting to pages from `fine-tuning` section

Reformat fine-tuning pages

---

fern/pages/text-generation/prompt-engineering/command-r7b-hf.mdx
fern/pages/text-generation/prompt-engineering/crafting-effective-prompts.mdx
fern/pages/text-generation/prompt-engineering/preambles.mdx
fern/pages/text-generation/prompt-engineering/prompt-library/add-a-docstring-to-your-code.mdx
fern/pages/text-generation/prompt-engineering/prompt-library/book-an-appointment.mdx
fern/pages/text-generation/prompt-engineering/prompt-library/create-a-markdown-table-from-raw-data.mdx
fern/pages/text-generation/prompt-engineering/prompt-library/create-csv-data-from-json-data.mdx
fern/pages/text-generation/prompt-engineering/prompt-library/evaluate-your-llm-response.mdx
fern/pages/text-generation/prompt-engineering/prompt-library/faster-web-search.mdx
fern/pages/text-generation/prompt-engineering/prompt-library/meeting-summarizer.mdx
fern/pages/text-generation/prompt-engineering/prompt-library/multilingual-interpreter.mdx
fern/pages/text-generation/prompt-engineering/prompt-library/remove-pii.mdx
fern/pages/text-generation/prompt-engineering/prompting-command-r.mdx

Applying `black` formatter to `text-generation` `prompt-engineering` section

Reformat text-generation prompt-engineering section

---

fern/pages/llm-university/intro-text-representation/classification-using-embeddings.mdx
fern/pages/llm-university/intro-text-representation/classify-endpoint.mdx
fern/pages/llm-university/intro-text-representation/clustering-hacker-news-posts.mdx
fern/pages/llm-university/intro-text-representation/clustering-using-embeddings.mdx
fern/pages/llm-university/intro-text-representation/clustering-with-embeddings.mdx
fern/pages/llm-university/intro-text-representation/embed-endpoint.mdx
fern/pages/llm-university/intro-text-representation/few-shot-classification.mdx
fern/pages/llm-university/intro-text-representation/fine-tuning-for-classification.mdx
fern/pages/llm-university/intro-text-representation/finetuning.mdx
fern/pages/llm-university/intro-text-representation/introduction-to-semantic-search.mdx
fern/pages/llm-university/intro-text-representation/introduction-to-text-embeddings.mdx
fern/pages/llm-university/intro-text-representation/setting-up.mdx
fern/pages/llm-university/sandbox/document-question-answering.mdx

Applying `black` formatter to `text representation` from LLM university.

Reformat code examples on llm university text-representation section

---

fern/pages/models/models.mdx

This PR updates the Amazon Bedrock Model ID, Amazon SageMaker, and Azure AI Studio Model ID for the `command-r7b-12-2024` model.
- The Amazon Bedrock Model ID is changed from `(Coming soon)` to `N/A`.
- The Amazon SageMaker is changed from `(Coming soon)` to `N/A`.
- The Azure AI Studio Model ID is changed from `(Coming soon)` to `N/A`.

Updating model tables.

---

fern/pages/llm-university/intro-deployment/deploying-with-aws-sagemaker.mdx
fern/pages/llm-university/intro-deployment/deploying-with-databutton.mdx
fern/pages/llm-university/intro-deployment/deploying-with-fastapi.mdx
fern/pages/llm-university/intro-deployment/deploying-with-streamlit.mdx

Appliying `black` reformatting to code examples in LLM University Deployments section

Reformat code examples for LLM Univeristy Deployments section

---

fern/pages/changelog/2022-02-22-larger-representation-models.mdx
fern/pages/changelog/2022-03-08-classification-endpoint.mdx
fern/pages/changelog/2022-04-25-new-extremely-large-model.mdx
fern/pages/changelog/2022-07-07-model-parameter-now-optional.mdx
fern/pages/changelog/2022-08-05-introducing-moderate-beta.mdx
fern/pages/changelog/2022-11-07-new-look-for-docs.mdx
fern/pages/changelog/2023-04-26-model-names-are-changing.mdx
fern/pages/changelog/2023-06-28-release-notes-june-28th-2023.mdx
fern/pages/changelog/2023-08-05-release-notes-august-4th-2023.mdx
fern/pages/changelog/2024-03-20-python-sdk-v500.mdx
fern/pages/changelog/2024-03-24-command-r-retrieval-augmented-generation-at-production-scale.mdx
fern/pages/changelog/2024-04-03-python-sdk-v520-release.mdx
fern/pages/changelog/2024-04-09-advanced-retrieval-launch.mdx
fern/pages/changelog/2024-06-10-release-notes-for-june-10th-2024.mdx
fern/pages/changelog/2024-09-26-refresh-models-on-azure.mdx

Update titles for `changelogs` to be in range of 30-60 chars

Update titles for changelogs 

---

fern/assets/input.css

This PR suggests an update of border color for the card container in dark mode.

✨ suggested styling update

---

fern/pages/cohere-api/about.mdx
fern/pages/cohere-api/errors.mdx
fern/pages/cohere-api/teams-and-roles.mdx
fern/pages/cookbooks/agent-api-calls.mdx
fern/pages/cookbooks/analyzing-hacker-news.mdx
fern/pages/cookbooks/article-recommender-with-text-embeddings.mdx
fern/pages/cookbooks/basic-multi-step.mdx
fern/pages/cookbooks/basic-rag.mdx
fern/pages/cookbooks/basic-semantic-search.mdx
fern/pages/cookbooks/basic-tool-use.mdx
fern/pages/cookbooks/chunking-strategies.mdx
fern/pages/cookbooks/embed-jobs-serverless-pinecone.mdx
fern/pages/cookbooks/finetune-on-sagemaker.mdx
fern/pages/cookbooks/hello-world-meet-ai.mdx
fern/pages/cookbooks/long-form-general-strategies.mdx

Updating page titles to be in range between 30-60 chars to fit SEO requirements

Update page titles to fit seo requirements

---

fern/pages/v2/deployment-options/cohere-on-aws/amazon-sagemaker-setup-guide.mdx

This PR adds a note to the Amazon SageMaker setup guide, informing users about the release of multimodal embeddings models that can handle images and text.
- The note provides a link to the documentation for more information.
- It is added after the code snippet that demonstrates embedding generation.

Mentioning image embeddings on SM V2.

---

fern/pages/tutorials/build-things-with-cohere.mdx
fern/pages/tutorials/build-things-with-cohere/building-a-chatbot-with-cohere.mdx
fern/pages/tutorials/build-things-with-cohere/building-an-agent-with-cohere.mdx
fern/pages/tutorials/build-things-with-cohere/rag-with-cohere.mdx
fern/pages/tutorials/build-things-with-cohere/reranking-with-cohere.mdx
fern/pages/tutorials/build-things-with-cohere/semantic-search-with-cohere.mdx
fern/pages/tutorials/build-things-with-cohere/text-generation-tutorial.mdx
fern/pages/tutorials/cohere-on-azure/azure-ai-rag.mdx
fern/pages/tutorials/cohere-on-azure/azure-ai-reranking.mdx
fern/pages/tutorials/cohere-on-azure/azure-ai-sem-search.mdx
fern/pages/tutorials/cohere-on-azure/azure-ai-text-generation.mdx
fern/pages/tutorials/cohere-on-azure/azure-ai-tool-use.mdx

Applying `black` formatter to pages from `tutorials` section

Reformat code samples formatting for tutorials pages

---

package.json

This change resolves the duplicate descriptions for /chat POST and SSE endpoints.

Bump fern Version.

---

package.json

Reverts cohere-ai/cohere-developer-experience#390

Revert "Bump fern Version."

---

fern/pages/deployment-options/single-container-on-private-clouds.mdx

Slight text change for support nvidia drivers version.

Updating nvidia supported drivers text

---

fern/pages/v2/tutorials/cohere-azure-ai-foundry.mdx
fern/pages/v2/tutorials/cohere-on-azure/azure-ai-rag.mdx
fern/pages/v2/tutorials/cohere-on-azure/azure-ai-reranking.mdx
fern/pages/v2/tutorials/cohere-on-azure/azure-ai-sem-search.mdx
fern/pages/v2/tutorials/cohere-on-azure/azure-ai-text-generation.mdx
fern/pages/v2/tutorials/cohere-on-azure/azure-ai-tool-use.mdx
fern/v2.yml
notebooks/guides/cohere-on-azure/v2/azure-ai-rag.ipynb
notebooks/guides/cohere-on-azure/v2/azure-ai-reranking.ipynb
notebooks/guides/cohere-on-azure/v2/azure-ai-sem-search.ipynb
notebooks/guides/cohere-on-azure/v2/azure-ai-text-generation.ipynb
notebooks/guides/cohere-on-azure/v2/azure-ai-tool-use.ipynb

This PR introduces a new page to the Cohere documentation, which provides an introduction to Cohere on Azure AI Foundry. It covers the following topics:
- What is Azure AI Foundry?
- Cohere Models on Azure AI Foundry
- Pricing Mechanisms
- Deploying Cohere's Models on Azure AI Foundry
- Conclusion
The page also includes a link to the Azure AI Foundry documentation for more information on deploying models.
Azure AI Foundry is a trusted platform that empowers developers to build and deploy innovative, responsible AI applications. It offers an enterprise-grade environment with cutting-edge tools and models, ensuring a safe and secure development process.
The platform facilitates collaboration, allowing teams to work together on the full lifecycle of application development. With Azure AI …

Add azure tutorials for API v2

---

fern/pages/deployment-options/private-deployment/private-deployment-usage.mdx
fern/pages/v2/deployment-options/deployment-options-overview.mdx
fern/pages/v2/deployment-options/private-deployment/private-deployment-overview.mdx
fern/pages/v2/deployment-options/private-deployment/private-deployment-setup.mdx
fern/pages/v2/deployment-options/private-deployment/private-deployment-usage.mdx
fern/pages/v2/deployment-options/private-deployment/single-container-on-private-clouds.mdx
fern/v1.yml
fern/v2.yml

This PR introduces a comprehensive guide to deploying and using Cohere's models in private environments, offering a range of deployment options and detailed setup instructions. The changes include:
- **Deployment Options Overview:** A new page provides an overview of the four deployment options: Cohere Platform, Cloud AI Services, Private Deployments (Cloud), and Private Deployments (On-Premises).
- **Private Deployment Overview:** This section explains what private deployments are, their benefits, and the components of Cohere's platform container.
- **Private Deployment Setup:** Details the process of setting up private deployments, including the information received upon signing up, infrastructure requirements, and available models.
- **Private Deployment Usage:** Provides instructions …

Add private deployment section

---

.github/workflows/check-python-code-snippets.yml
fern/pages/deployment-options/private-deployment/private-deployment-usage.mdx
fern/pages/get-started/quickstart/rag-quickstart.mdx
fern/pages/get-started/quickstart/reranking-quickstart.mdx
fern/pages/get-started/quickstart/sem-search-quickstart.mdx
fern/pages/get-started/quickstart/text-gen-quickstart.mdx
fern/pages/get-started/quickstart/tool-use-quickstart.mdx
fern/pages/v2/deployment-options/private-deployment/private-deployment-usage.mdx
fern/pages/v2/get-started/quickstart/rag-quickstart.mdx
fern/pages/v2/get-started/quickstart/reranking-quickstart.mdx
fern/pages/v2/get-started/quickstart/sem-search-quickstart.mdx
fern/pages/v2/get-started/quickstart/text-gen-quickstart.mdx
fern/pages/v2/get-started/quickstart/tool-use-quickstart.mdx
fern/pages/v2/tutorials/cohere-on-azure/azure-ai-rag.mdx

I found issue with python code snippets pipeline was hiding results from other pipelines on commit changes so I want to remove temporarily step with auto-commit changes and replace it with manual exercice.

Fixing issue with format code snippets pipeline

---

fern/pages/deployment-options/private-deployment/private-deployment-usage.mdx
fern/pages/get-started/quickstart/rag-quickstart.mdx
fern/pages/get-started/quickstart/reranking-quickstart.mdx
fern/pages/get-started/quickstart/sem-search-quickstart.mdx
fern/pages/get-started/quickstart/text-gen-quickstart.mdx
fern/pages/get-started/quickstart/tool-use-quickstart.mdx
fern/pages/v2/deployment-options/private-deployment/private-deployment-usage.mdx
fern/pages/v2/deployment-options/private-deployment/single-container-on-private-clouds.mdx
fern/pages/v2/get-started/quickstart/rag-quickstart.mdx
fern/pages/v2/get-started/quickstart/reranking-quickstart.mdx
fern/pages/v2/get-started/quickstart/sem-search-quickstart.mdx
fern/pages/v2/get-started/quickstart/text-gen-quickstart.mdx
fern/pages/v2/get-started/quickstart/tool-use-quickstart.mdx

add example to update docker cli configuration only for the current terminal session
source url: https://docs.cohere.com/v2/docs/single-container-on-private-clouds

add example to update docker cli configuration only for the current terminal session

---

fern/pages/v2/get-started/quickstart/rag-quickstart.mdx
fern/pages/v2/get-started/quickstart/reranking-quickstart.mdx
fern/pages/v2/get-started/quickstart/sem-search-quickstart.mdx
fern/pages/v2/get-started/quickstart/text-gen-quickstart.mdx
fern/pages/v2/get-started/quickstart/tool-use-quickstart.mdx
fern/pages/v2/tool-use/tool-use-citations.mdx
fern/pages/v2/tool-use/tool-use-overview.mdx
fern/pages/v2/tool-use/tool-use-parameter-types.mdx
fern/pages/v2/tool-use/tool-use-streaming.mdx
fern/pages/v2/tool-use/tool-use-usage-patterns.mdx
fern/pages/v2/tutorials/cohere-on-azure/azure-ai-rag.mdx
fern/pages/v2/tutorials/cohere-on-azure/azure-ai-reranking.mdx
fern/pages/v2/tutorials/cohere-on-azure/azure-ai-sem-search.mdx
fern/pages/v2/tutorials/cohere-on-azure/azure-ai-text-generation.mdx
fern/pages/v2/tutorials/cohere-on-azure/azure-ai-tool-use.mdx

This pull request updates the titles and descriptions of several quickstart guides and tutorials for Cohere's Command, Reranking, and Embed models. The changes ensure consistency in the naming conventions and provide clearer information about the content of each guide.
- The titles of the quickstart guides for Retrieval Augmented Generation (RAG), Reranking, Semantic Search, and Text Generation have been updated to include the term 'quickstart' for clarity.
- The titles of the tutorials for RAG, Reranking, Semantic Search, and Text Generation on Azure AI Foundry have been modified to specify the platform and technology stack.
- The descriptions of all the guides have been adjusted to accurately reflect the content and purpose of each document.

Update titles for quickstart pages and Azure AI tutorials

---

fern/pages/changelog/2025-02-26-compatibility-api.mdx
fern/pages/v2/text-generation/compatibility-api.mdx
fern/v2.yml

The pull request introduces the Compatibility API, which allows developers to use Cohere's models through OpenAI's SDK without significant refactoring. It includes comprehensive support for chat completions, function calling, structured outputs, and text embeddings generation.
The changes include:
- Adding a new file `fern/pages/changelog/2025-02-26-compatibility-api.mdx` that provides an overview of the Compatibility API and its benefits.
- Creating a new file `fern/pages/v2/text-generation/compatibility-api.mdx` that serves as a guide for using the Compatibility API, including installation instructions and code examples in Python, TypeScript, and cURL.
- Updating the `fern/v2.yml` file to include a new page entry for the Compatibility API documentation.

Add compatibility API docs

---

fern/pages/deployment-options/north-eap-private-deployment.mdx
fern/v1.yml
fern/v2.yml

This pull request introduces a new document titled "North EAP - Private Deployments", which provides a comprehensive guide for installing North in a POC environment. The document outlines the necessary requirements, installation steps, and configuration options for a successful deployment.
- **Requirements:** The PR specifies the hardware, cluster, and external resources needed for the installation, including Kubernetes Cluster, CPU and GPU compute, storage, and various dependencies.
- **Installation:** A detailed step-by-step installation process is provided, covering namespace creation, dependency installation, secret creation, and helm chart deployment.
- **Configuration Options:** Advanced configuration options are presented, including OIDC authentication, Postgres and Redis/Valkey …

Adding the document.

---

fern/pages/changelog/2025-03-04-aya-vision-is-here.mdx

This pull request updates the release announcement for the new multimodal Aya Vision model. The changes include:
- Adding a link to the blog post about Aya Vision.
- Emphasising the model's performance in critical benchmarks for language, text, and image capabilities.
- Highlighting the model's support for tasks such as image captioning, visual question answering, text generation, and translations from both texts and images into coherent text.

Fast follow for a typo.

---

fern/assets/input.css

Reverts cohere-ai/cohere-developer-experience#439

Revert "Fix Learn more text color"

---

fern/pages/get-started/the-cohere-platform.mdx
fern/pages/models/the-command-family-of-models/command-r7b.mdx
fern/pages/text-generation/prompt-engineering/crafting-effective-prompts.mdx
fern/pages/text-generation/prompt-engineering/prompt-library/add-a-docstring-to-your-code.mdx
fern/pages/text-generation/prompt-engineering/prompt-library/book-an-appointment.mdx
fern/pages/text-generation/prompt-engineering/prompt-library/create-a-markdown-table-from-raw-data.mdx
fern/pages/text-generation/prompt-engineering/prompt-library/create-csv-data-from-json-data.mdx
fern/pages/text-generation/prompt-engineering/prompt-library/evaluate-your-llm-response.mdx
fern/pages/text-generation/prompt-engineering/prompt-library/faster-web-search.mdx
fern/pages/text-generation/prompt-engineering/prompt-library/meeting-summarizer.mdx
fern/pages/text-generation/prompt-engineering/prompt-library/multilingual-interpreter.mdx
fern/pages/text-generation/prompt-engineering/prompt-library/remove-pii.mdx
fern/pages/text-generation/streaming.mdx

This PR updates the Cohere Platform documentation by changing the URL for the Command family of models and removing the word "final" from the description of Command R7B.
**Files walkthrough**
- fern/pages/get-started/the-cohere-platform.mdx: Changes the URL for the Command family of models.
- fern/pages/models/the-command-family-of-models/command-r7b.mdx: Removes the word "final" from the description of Command R7B.
- fern/pages/text-generation/prompt-engineering/crafting-effective-prompts.mdx: Adds a new line for the model parameter in the code snippet.
- fern/pages/text-generation/prompt-engineering/prompt-library/add-a-docstring-to-your-code.mdx: Adds the model parameter to the code snippet.
- fern/pages/text-generation/prompt-engineering/prompt-library/book-an-appointment.mdx: Adds …

Command a misc changes

---

fern/pages/cohere-api/create-an-api-key.mdx
fern/pages/llm-university/intro-building-apps/app-examples.mdx
fern/pages/llm-university/intro-semantic-search/further-reading-search.mdx
fern/pages/llm-university/intro-the-cohere-platform/endpoints.mdx
fern/v2.yml

This PR aims to fix broken links reported by brokenLinks tool from this [PR](https://github.com/cohere-ai/cohere-developer-experience/pull/428)
There's still one unresolved issue with `/docs/multi-step-tool-use`

Fix broken links reported by brokenLinks tool

---

fern/pages/models/aya-multimodal.mdx

**Description**
The title and slug of the Aya Multimodal page have been changed to Aya Vision and docs/aya-vision respectively.
**Changes**
- The title and slug of the Aya Multimodal page have been changed to Aya Vision and docs/aya-vision respectively.

Changing slug, title.

---

fern/docs.yml

**Description**
The PR updates the redirects section of the docs.yml file.
**Changes**
- A new redirect is added to the redirects section of the docs.yml file.
- The new redirect source is /docs/aya-multimodal, and the destination is /docs/aya-vision, with a permanent status of true.

Set redirect for aya vision

---

fern/pages/cookbooks/hello-world-meet-ai.mdx
fern/pages/get-started/frequently-asked-questions.mdx
fern/pages/get-started/installation.mdx
fern/pages/llm-university/intro-text-generation/the-generate-endpoint.mdx
fern/pages/llm-university/intro-text-representation/setting-up.mdx
fern/pages/llm-university/sandbox/chapter-1-how-to-use-coheres-endpoints-copy-copy-copy.mdx
fern/pages/tutorials/build-things-with-cohere.mdx
fern/pages/v2/tutorials/build-things-with-cohere.mdx
notebooks/guides/Hello_World_Meet_Language_AI.ipynb
notebooks/guides/getting-started/tutorial_pt1.ipynb
notebooks/guides/getting-started/v2/tutorial_pt1_v2.ipynb
notebooks/llmu/Embed_Endpoint.ipynb

Since cli tool has been deprecated we want to remove all the mentions on docs.

Remove cli tool mentions

---

fern/pages/text-generation/structured-outputs.mdx
fern/pages/v2/text-generation/structured-outputs.mdx

This PR updates the description and keywords of the structured-outputs.mdx file.
- The description now includes a reference to the `response_format` parameter.
- The keywords now include a reference to the `response format parameter`.

Changing the page to make the search results better.

---

fern/pages/text-generation/prompt-engineering/preambles.mdx

This PR removes the JSON formatting from the sample output.
- Removes JSON formatting from sample output

Update preamble output example

---

notebooks/guides/Document_Parsing_For_Enterprises.ipynb

This PR updates the Document_Parsing_For_Enterprises.ipynb file.
- The `doc_content = doc.read()\` line is indented

indent "doc_content" inside function

---

fern/pages/integrations/integrations/weaviate-and-cohere.mdx

This PR updates the Weaviate and Cohere integration guide by adding new sections and code snippets to demonstrate the integration of Cohere's Embed, Rerank, and Command models with Weaviate's vector database.
- Adds a new section on setting up a Weaviate cluster and connecting to it using the Weaviate Python client.
- Introduces a new collection named "Healthcare_Compliance" in the Weaviate database and demonstrates how to add healthcare compliance documents to it.
- Adds a section on performing a near_text search for documents related to a specific query and printing the results with distance metadata.
- Introduces Cohere Rerank to improve search results by reordering them based on relevance.
- Adds a new collection named "Legal_Docs" in the Weaviate database and demonstrates how to add …

Updating the Weaviate integration notebook.

---

fern/pages/integrations/integrations/weaviate-and-cohere.mdx

In scope of this [PR](https://github.com/cohere-ai/cohere-developer-experience/pull/535) pages has been modified but pipelines that should validate code snippets hasn't been triggered

Fix broken weaviate mdx page

---

fern/pages/v2/get-started/quickstart/text-gen-quickstart.mdx
fern/pages/v2/get-started/quickstart/tool-use-quickstart.mdx

This PR refactors the code to append the model's response to the messages and append another user message to the messages. It also removes the need to check if a chunk exists before checking its type.
**Changes:**
- Refactored code to append the model's response and another user message to the messages.
- Removed the need to check if a chunk exists before checking its type.
- Simplified the code for handling tool calls by directly appending the response message.

Update snippets quickstart guides - text generation and tool use

---

fern/pages/text-embeddings/embeddings.mdx

This PR updates the `calculate_similarity` function in the `embeddings.mdx` file.
- The function now prints the similarity score for three sentences instead of two.
- The third sentence is added to the print statement and the similarity score is calculated using the `calculate_similarity` function.

fix snippets syntax
